package io.kitchen.meater.data

import android.content.Context
import org.json.JSONObject

/**
 * Provides the cooking tree and doneness options for the cut selection UI.
 *
 * Data is read at runtime from the bundled kitchen-cooking-panel.js asset.
 * That file is the single source of truth — generated by generate_frontend_data.py
 * from the www/recipes/ KCE:CUT markdown files.
 *
 * Tree hierarchy mirrors KCE: category → species (meats) → cutType → cuts.
 *
 * Whenever cut files are added, removed, or changed:
 *   1. Run: python3 generate_frontend_data.py
 *   2. Rebuild the APK
 *
 * No separate cooking_data.json is used or needed.
 */
class CookingDataRepository(private val context: Context) {

    data class ProteinCategory(
        val id: String,
        val name: String,
        val nameSv: String,
        val icon: String,
        val color: String,
        val species: List<Species>
    )

    data class Species(
        val id: String,
        val name: String,
        val nameSv: String,
        val cutTypes: List<CutType>
    )

    data class CutType(
        val id: String,
        val name: String,
        val nameSv: String,
        val cuts: List<Cut>
    )

    data class Cut(
        val id: String,
        val name: String,
        val nameSv: String,
        val slug: String,
        val doneness: List<String>,
        val recommendedDoneness: String,
        val supportedMethods: List<String>,
        val usdaSafeC: Int,
        val restTimeMin: Int,
        val restTimeMax: Int,
        val carryoverTempC: Int
    )

    data class DonenessOption(
        val value: String,
        val name: String,
        val nameSv: String,
        val icon: String,
        val tempC: Int,
        val tempF: Int,
        val safetyLevel: String
    )

    // Load once; cache both tree and doneness together to avoid reading the 7 MB asset twice.
    private var cached: Pair<List<ProteinCategory>, Map<String, DonenessOption>>? = null

    private fun loadOnce(): Pair<List<ProteinCategory>, Map<String, DonenessOption>> =
        cached ?: load().also { cached = it }

    val tree: List<ProteinCategory>
        get() = loadOnce().first

    val doneness: Map<String, DonenessOption>
        get() = loadOnce().second

    // Recipe titles: slug → method → list of recipe titles
    // Loaded lazily from RECIPE_TITLES_INDEX in kitchen-cooking-panel.js
    private var cachedRecipeTitles: Map<String, Map<String, List<String>>>? = null

    val recipeTitles: Map<String, Map<String, List<String>>>
        get() = cachedRecipeTitles ?: loadRecipeTitles().also { cachedRecipeTitles = it }

    private fun loadRecipeTitles(): Map<String, Map<String, List<String>>> {
        val js = try {
            context.assets.open("kitchen-cooking-panel.js").bufferedReader().readText()
        } catch (_: Exception) { return emptyMap() }
        val json = extractJsonObject(js, "RECIPE_TITLES_INDEX") ?: return emptyMap()
        val result = mutableMapOf<String, Map<String, List<String>>>()
        for (slug in json.keys()) {
            val methodsObj = try { json.getJSONObject(slug) } catch (_: Exception) { continue }
            val methodMap = mutableMapOf<String, List<String>>()
            for (method in methodsObj.keys()) {
                val arr = try { methodsObj.getJSONArray(method) } catch (_: Exception) { continue }
                methodMap[method] = (0 until arr.length()).map { arr.getString(it) }
            }
            result[slug] = methodMap
        }
        return result
    }

    private fun load(): Pair<List<ProteinCategory>, Map<String, DonenessOption>> {
        val js = try {
            context.assets.open("kitchen-cooking-panel.js").bufferedReader().readText()
        } catch (_: Exception) {
            return emptyList<ProteinCategory>() to emptyMap()
        }

        val treeJson = extractJsonObject(js, "EXP_TREE")
            ?: return emptyList<ProteinCategory>() to emptyMap()
        val donenessJson = extractJsonObject(js, "EXP_DONENESS_OPTIONS")
            ?: JSONObject()

        val categories = mutableListOf<ProteinCategory>()
        for (catKey in treeJson.keys()) {
            val cat = treeJson.getJSONObject(catKey)
            val speciesList = mutableListOf<Species>()

            val meatsJson = cat.optJSONArray("meats") ?: continue
            for (mi in 0 until meatsJson.length()) {
                val meat = meatsJson.getJSONObject(mi)
                val cutTypesList = mutableListOf<CutType>()

                val typesJson = meat.optJSONArray("cutTypes") ?: continue
                for (ti in 0 until typesJson.length()) {
                    val cutTypeObj = typesJson.getJSONObject(ti)
                    val cutsJson = cutTypeObj.optJSONArray("cuts") ?: continue
                    val cuts = mutableListOf<Cut>()

                    for (ci in 0 until cutsJson.length()) {
                        val cut = cutsJson.getJSONObject(ci)
                        val donenessArr = cut.optJSONArray("doneness")
                        val donenessIds = if (donenessArr != null) {
                            (0 until donenessArr.length()).map { donenessArr.getString(it) }
                        } else emptyList()

                        val methodsArr = cut.optJSONArray("supported_methods")
                        val methods = if (methodsArr != null) {
                            (0 until methodsArr.length()).map { methodsArr.getString(it) }
                        } else emptyList()

                        cuts.add(Cut(
                            id = cut.optString("id"),
                            name = cut.optString("name"),
                            nameSv = cut.optString("name_sv"),
                            slug = cut.optString("slug"),
                            doneness = donenessIds,
                            recommendedDoneness = cut.optString("recommended_doneness"),
                            supportedMethods = methods,
                            usdaSafeC = cut.optInt("usda_safe_c", 0),
                            restTimeMin = cut.optInt("rest_time_min", 0),
                            restTimeMax = cut.optInt("rest_time_max", 0),
                            carryoverTempC = cut.optInt("carryover_temp_c", 0)
                        ))
                    }

                    cutTypesList.add(CutType(
                        id = cutTypeObj.optString("id"),
                        name = cutTypeObj.optString("name"),
                        nameSv = cutTypeObj.optString("name_sv", cutTypeObj.optString("name")),
                        cuts = cuts
                    ))
                }

                speciesList.add(Species(
                    id = meat.optString("id"),
                    name = meat.optString("name"),
                    nameSv = meat.optString("name_sv", meat.optString("name")),
                    cutTypes = cutTypesList
                ))
            }

            categories.add(ProteinCategory(
                id = cat.optString("id"),
                name = cat.optString("name"),
                nameSv = cat.optString("name_sv", cat.optString("name")),
                icon = cat.optString("icon"),
                color = cat.optString("color", "#888"),
                species = speciesList
            ))
        }

        val donenessMap = mutableMapOf<String, DonenessOption>()
        for (key in donenessJson.keys()) {
            val d = donenessJson.getJSONObject(key)
            donenessMap[key] = DonenessOption(
                value = d.optString("value", key),
                name = d.optString("name"),
                nameSv = d.optString("name_sv", d.optString("name")),
                icon = d.optString("icon", "\uD83C\uDF21\uFE0F"),
                tempC = d.optInt("temp_c"),
                tempF = d.optInt("temp_f"),
                safetyLevel = d.optString("safety_level", "")
            )
        }

        return categories to donenessMap
    }

    /**
     * Extract the JSON object assigned to [varName] from a JS file.
     * Matches: const <varName> = { ... };
     * Uses brace counting to find the exact end of the object.
     */
    private fun extractJsonObject(js: String, varName: String): JSONObject? {
        val marker = "const $varName = {"
        val start = js.indexOf(marker)
        if (start < 0) return null
        val objectStart = start + marker.length - 1  // position of opening '{'

        var depth = 0
        var inString = false
        var escape = false
        var i = objectStart

        while (i < js.length) {
            val c = js[i]
            when {
                escape -> escape = false
                inString && c == '\\' -> escape = true
                c == '"' -> inString = !inString
                !inString && c == '{' -> depth++
                !inString && c == '}' -> {
                    depth--
                    if (depth == 0) {
                        return try {
                            JSONObject(js.substring(objectStart, i + 1))
                        } catch (_: Exception) {
                            null
                        }
                    }
                }
            }
            i++
        }
        return null
    }
}
