package io.kitchen.meater.data

import android.content.Context
import org.json.JSONObject

/**
 * Loads the cooking tree data bundled as an APK asset (cooking_data.json).
 * The asset is generated by generate_frontend_data.py and copied at build time.
 *
 * Data shape mirrors EXP_TREE and EXP_DONENESS_OPTIONS from kitchen-cooking-panel.js.
 */
class CookingDataRepository(private val context: Context) {

    data class ProteinCategory(
        val id: String,
        val name: String,
        val nameSv: String,
        val icon: String,
        val color: String,
        val cuts: List<Cut>
    )

    data class Cut(
        val id: String,
        val name: String,
        val nameSv: String,
        val slug: String,
        val doneness: List<String>,
        val recommendedDoneness: String
    )

    data class DonenessOption(
        val value: String,
        val name: String,
        val nameSv: String,
        val icon: String,
        val tempC: Int,
        val tempF: Int,
        val safetyLevel: String
    )

    private var _tree: List<ProteinCategory>? = null
    private var _doneness: Map<String, DonenessOption>? = null

    val tree: List<ProteinCategory>
        get() = _tree ?: load().first.also { _tree = it }

    val doneness: Map<String, DonenessOption>
        get() = _doneness ?: load().second.also { _doneness = it }

    private fun load(): Pair<List<ProteinCategory>, Map<String, DonenessOption>> {
        val json = context.assets.open("cooking_data.json").bufferedReader().readText()
        val root = JSONObject(json)

        val treeJson = root.getJSONObject("tree")
        val categories = mutableListOf<ProteinCategory>()

        for (catKey in treeJson.keys()) {
            val cat = treeJson.getJSONObject(catKey)
            val cuts = mutableListOf<Cut>()

            val meatsJson = cat.optJSONArray("meats") ?: continue
            for (mi in 0 until meatsJson.length()) {
                val meat = meatsJson.getJSONObject(mi)
                val typesJson = meat.optJSONArray("cutTypes") ?: continue
                for (ti in 0 until typesJson.length()) {
                    val cutType = typesJson.getJSONObject(ti)
                    val cutsJson = cutType.optJSONArray("cuts") ?: continue
                    for (ci in 0 until cutsJson.length()) {
                        val cut = cutsJson.getJSONObject(ci)
                        val donenessArr = cut.optJSONArray("doneness")
                        val donenessIds = if (donenessArr != null) {
                            (0 until donenessArr.length()).map { donenessArr.getString(it) }
                        } else emptyList()

                        cuts.add(Cut(
                            id = cut.optString("id"),
                            name = cut.optString("name"),
                            nameSv = cut.optString("name_sv"),
                            slug = cut.optString("slug"),
                            doneness = donenessIds,
                            recommendedDoneness = cut.optString("recommended_doneness")
                        ))
                    }
                }
            }

            categories.add(ProteinCategory(
                id = cat.optString("id"),
                name = cat.optString("name"),
                nameSv = cat.optString("name", cat.optString("id")),
                icon = cat.optString("icon"),
                color = cat.optString("color", "#888"),
                cuts = cuts
            ))
        }

        val donenessJson = root.getJSONObject("doneness")
        val donenessMap = mutableMapOf<String, DonenessOption>()
        for (key in donenessJson.keys()) {
            val d = donenessJson.getJSONObject(key)
            donenessMap[key] = DonenessOption(
                value = d.optString("value"),
                name = d.optString("name"),
                nameSv = d.optString("name_sv", d.optString("name")),
                icon = d.optString("icon", "🌡️"),
                tempC = d.optInt("temp_c"),
                tempF = d.optInt("temp_f"),
                safetyLevel = d.optString("safety_level", "")
            )
        }

        return categories to donenessMap
    }
}
