# MEATER+ BLE Client Configuration
# This configuration reads temperature data from a real MEATER+ probe via BLE
# and exposes the data to Home Assistant. No cloud connection required.
#
# The BLE server emulation (for MEATER app compatibility) has been put on hold.
# See docs/TERMS_OF_REFERENCE.md for the Kitchen Cooking Engine project vision.

esphome:
  name: meater
  friendly_name: meater

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# BLE proxy allows Home Assistant to see other BLE devices through this ESP32
bluetooth_proxy:

# BLE client to connect to the real MEATER+ probe
ble_client:
  - mac_address: !secret meater_mac_address
    id: meater
    on_connect:
      then:
        - lambda: 'id(meater_connected) = true;'
        - script.execute: update_status_led
    on_disconnect:
      then:
        - lambda: 'id(meater_connected) = false;'
        - script.execute: update_status_led

# Global variable to track MEATER connection status
globals:
  - id: meater_connected
    type: bool
    initial_value: 'false'

text_sensor:
  - platform: template
    name: "MEATER firmware"
    id: meater_firmware

sensor:
  # Tip temperature - internal meat temperature
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER tip temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip_temp = (x[0] + (x[1] << 8) + 8.0) / 16.0;
      return (float)tip_temp;

  # Ambient temperature - oven/grill environment temperature
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER ambient temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip = x[0] + (x[1] << 8);
      uint16_t ra = x[2] + (x[3] << 8);
      uint16_t oa = x[4] + (x[5] << 8);
      uint16_t min_val = 48;
      uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
      return (float)ambient;

  # Battery level
  # Battery data is 2 bytes: byte0 + byte1*256 gives raw value, multiply by 10 for percentage
  # Reference: https://github.com/nathanfaber/meaterble
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER battery level"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '2adb4877-68d8-4884-bd3c-d83853bf27b8'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    notify: true
    lambda: |-
      uint16_t battery = (x[0] + (x[1] << 8)) * 10;
      return (float)battery;

  # Firmware version reader
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    id: firmware
    service_uuid: '180A'
    characteristic_uuid: '00002a26-0000-1000-8000-00805f9b34fb'
    lambda: |-
      std::string data_string(x.begin(), x.end());
      id(meater_firmware).publish_state(data_string.c_str());
      return (float)x.size();

  # RSSI signal strength
  - platform: ble_client
    type: rssi
    ble_client_id: meater
    name: "MEATER RSSI"

# Onboard RGB LED (WS2812) on ESP32-C3-DevKitM-1
# Status indicator:
#   - Red: Not connected to WiFi
#   - Green: Connected to both WiFi and MEATER probe
#   - Off: Connected to WiFi but not connected to MEATER probe
light:
  - platform: esp32_rmt_led_strip
    id: onboard_led
    name: "MEATER Status LED"
    pin: GPIO8
    num_leds: 1
    chipset: WS2812
    rgb_order: GRB
    rmt_channel: 0

# Script to update LED based on connection status
script:
  - id: update_status_led
    then:
      - if:
          condition:
            not:
              wifi.connected:
          then:
            # Red: Not connected to WiFi
            - light.turn_on:
                id: onboard_led
                red: 100%
                green: 0%
                blue: 0%
                brightness: 100%
          else:
            - if:
                condition:
                  lambda: 'return id(meater_connected);'
                then:
                  # Green: Connected to both WiFi and MEATER
                  - light.turn_on:
                      id: onboard_led
                      red: 0%
                      green: 100%
                      blue: 0%
                      brightness: 100%
                else:
                  # Off: Connected to WiFi but not MEATER
                  - light.turn_off:
                      id: onboard_led

# Update LED status periodically and on WiFi state changes
interval:
  - interval: 5s
    then:
      - script.execute: update_status_led
