substitutions:
  meater_mac: !secret meater_mac_address

esphome:
  name: meater
  friendly_name: meater
  includes:
    - includes/meater_ble_server.h
    - includes/meater_nimble_client.h
  on_boot:
    priority: -10
    then:
      - lambda: |-
          ESP_LOGI("meater", "Initializing NimBLE BLE server and client");
          
          // Initialize BLE server for phone app
          if (id(meater_ble_server_ptr) == nullptr) {
            static MeaterBLEServer* server = new MeaterBLEServer();
            server->setup();
            id(meater_ble_server_ptr) = (void*)server;
          }
          
          // Initialize BLE client for connecting to real MEATER+
          if (id(meater_client_ptr) == nullptr) {
            std::string mac = "${meater_mac}";
            static MeaterNimBLEClient* client = new MeaterNimBLEClient(mac);
            
            // Set up temperature callback
            client->set_on_temp_update([](const std::vector<uint8_t>& data) {
              // Forward to BLE server
              if (id(meater_ble_server_ptr) != nullptr) {
                ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_temp_data(data);
              }
              
              // Calculate and publish tip temperature
              if (data.size() >= 2) {
                uint16_t tip_temp = (data[0] + (data[1] << 8) + 8.0) / 16.0;
                id(meater_tip_temp).publish_state((float)tip_temp);
              }
              
              // Calculate and publish ambient temperature
              if (data.size() >= 6) {
                uint16_t tip = data[0] + (data[1] << 8);
                uint16_t ra = data[2] + (data[3] << 8);
                uint16_t oa = data[4] + (data[5] << 8);
                uint16_t min_val = 48;
                uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
                id(meater_ambient_temp).publish_state((float)ambient);
              }
            });
            
            // Set up battery callback
            client->set_on_battery_update([](const std::vector<uint8_t>& data) {
              // Forward to BLE server
              if (id(meater_ble_server_ptr) != nullptr) {
                ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_battery_data(data);
              }
              
              // Calculate and publish battery level
              if (data.size() >= 2) {
                uint16_t battery = (data[0] + data[1]) * 10;
                id(meater_battery).publish_state((float)battery);
              }
            });
            
            // Set up firmware callback
            client->set_on_firmware_update([](const std::vector<uint8_t>& data) {
              // Forward to BLE server
              if (id(meater_ble_server_ptr) != nullptr) {
                ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_firmware_data(data);
              }
              
              // Publish firmware string
              std::string firmware_str(data.begin(), data.end());
              id(meater_firmware).publish_state(firmware_str);
            });
            
            // Set up device name callback
            client->set_on_device_name_update([](const std::vector<uint8_t>& data) {
              // Update device name display
              std::string device_name(data.begin(), data.end());
              id(meater_device_name_display).publish_state(device_name);
              
              // Update BLE server device name
              if (id(meater_ble_server_ptr) != nullptr) {
                ((MeaterBLEServer*)id(meater_ble_server_ptr))->set_device_name(device_name);
              }
            });
            
            id(meater_client_ptr) = (void*)client;
            
            // Start scanning for MEATER device
            client->start_scan();
          }

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      # Pure NimBLE configuration for ESP32-C6
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLUEDROID_ENABLED: n  # Explicitly disable Bluedroid
      CONFIG_BT_NIMBLE_ENABLED: y
      CONFIG_BT_NIMBLE_ROLE_CENTRAL: y
      CONFIG_BT_NIMBLE_ROLE_PERIPHERAL: y
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "4"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# Text sensors for firmware and device name
text_sensor:
  - platform: template
    name: "MEATER firmware"
    id: meater_firmware
  - platform: template
    name: "MEATER device name"
    id: meater_device_name_display

# Template sensors that will be updated by NimBLE client callbacks
sensor:
  - platform: template
    name: "MEATER tip temperature"
    id: meater_tip_temp
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
  
  - platform: template
    name: "MEATER ambient temperature"
    id: meater_ambient_temp
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
  
  - platform: template
    name: "MEATER battery level"
    id: meater_battery
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    accuracy_decimals: 0

# Global variables to store BLE instances
globals:
  - id: meater_ble_server_ptr
    type: void*
    restore_value: no
    initial_value: 'nullptr'
  - id: meater_client_ptr
    type: void*
    restore_value: no
    initial_value: 'nullptr'
