esphome:
  name: meater
  friendly_name: meater
  includes:
    - includes/meater_ble_server.h
  # Note: BLE server initialization is now delayed until after BLE client connects
  # This prevents conflicts between BLE scanning and advertising

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

esp32_ble:
  max_connections: 4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

bluetooth_proxy:

ble_client:
  - mac_address: !secret meater_mac_address
    id: meater

 
text_sensor:
  - platform: template
    name: "MEATER firmware"
    id: meater_firmware
 
sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER tip temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      // Initialize BLE server on first data reception (ensures BLE client is connected first)
      static bool ble_server_initialized = false;
      if (!ble_server_initialized && id(meater_ble_server_ptr) == nullptr) {
        ESP_LOGI("meater", "BLE client connected, now initializing BLE server...");
        static MeaterBLEServer* ble_server = new MeaterBLEServer();
        ble_server->setup();
        id(meater_ble_server_ptr) = (void*)ble_server;
        ble_server_initialized = true;
      }
      
      // Forward raw data to BLE server for phone app
      if (id(meater_ble_server_ptr) != nullptr) {
        ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_temp_data(x);
      }
      
      // Calculate temperature for Home Assistant (existing functionality)
      uint16_t tip_temp = (x[0] + (x[1] << 8) + 8.0) / 16.0;
      return (float)tip_temp;
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER ambient temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      // Calculate ambient temperature for Home Assistant (existing functionality)
      uint16_t tip = x[0] + (x[1] << 8);
      uint16_t ra = x[2] + (x[3] << 8);
      uint16_t oa = x[4] + (x[5] << 8);
      uint16_t min_val = 48;
      uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
      return (float)ambient;
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    name: "MEATER battery level"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '2adb4877-68d8-4884-bd3c-d83853bf27b8'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    notify: true
    lambda: |-
      // Forward raw data to BLE server for phone app
      if (id(meater_ble_server_ptr) != nullptr) {
        ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_battery_data(x);
      }
      
      // Calculate battery percentage for Home Assistant (existing functionality)
      uint16_t battery = (x[0] + x[1]) * 10;
      return (float)battery;
  - platform: ble_client
    type: characteristic
    ble_client_id: meater
    id: firmware
    service_uuid: '180A'
    characteristic_uuid: '00002a26-0000-1000-8000-00805f9b34fb'
    lambda: |-
      // Update firmware text sensor (existing functionality)
      std::string data_string(x.begin(), x.end());
      id(meater_firmware).publish_state(data_string.c_str());
      
      // Forward firmware data to BLE server for phone app
      if (id(meater_ble_server_ptr) != nullptr) {
        ((MeaterBLEServer*)id(meater_ble_server_ptr))->update_firmware_data(x);
      }
      
      return (float)x.size();
  - platform: ble_client
    type: rssi
    ble_client_id: meater
    name: "MEATER RSSI"

# Global variable to store the BLE server instance
globals:
  - id: meater_ble_server_ptr
    type: void*
    restore_value: no
    initial_value: 'nullptr'
