esphome:
  name: meater
  friendly_name: meater
  includes:
    - includes/meater_bluedroid_server.h
  on_boot:
    # Priority 600 ensures this runs early, before other components
    # Higher priority = runs earlier (default components run at priority 0-100)
    priority: 600
    then:
      - lambda: |-
          ESP_LOGI("meater", "=== BOOT: Initializing MEATER BLE probe (BLE only, no UDP) ===");
      - script.execute: init_ble_server
      - delay: 1s
      - lambda: |-
          ESP_LOGI("meater", "=== BOOT: BLE server initialization complete ===");

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_ENABLED: y
      CONFIG_BT_BLUEDROID_ENABLED: y
      CONFIG_BT_CLASSIC_ENABLED: n
      CONFIG_BT_NIMBLE_ENABLED: n
      CONFIG_BTDM_CTRL_MODE_BLE_ONLY: y
      CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY: n
      CONFIG_BTDM_CTRL_MODE_BTDM: n
      CONFIG_BT_RESERVE_DRAM: "0x10000"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# BLE TRACKER DISABLED - conflicts with BLE server mode
# The BLE server initializes Bluedroid directly
# esp32_ble_tracker:
#   scan_parameters:
#     active: false

# BLE CLIENT REMOVED - see meater_ble_client_backup.yaml for restoration
# ble_client:
#   - mac_address: !secret meater_mac_address
#     id: meater

# Global variable to store the BLE server instance
globals:
  - id: ble_server_ptr
    type: void*
    restore_value: no
    initial_value: 'nullptr'

# Initialize BLE server on boot
script:
  - id: init_ble_server
    then:
      - lambda: |-
          static bool ble_initialized = false;
          if (!ble_initialized && id(ble_server_ptr) == nullptr) {
            ESP_LOGI("meater", "Initializing MEATER BLE probe (standalone)");
            static MeaterBluedroidServer* ble_server = new MeaterBluedroidServer();
            if (ble_server->setup()) {
              id(ble_server_ptr) = (void*)ble_server;
              ble_initialized = true;
              ESP_LOGI("meater", "✓ MEATER BLE probe started - advertising as 'MEATER'");
              
              // Set initial firmware and device name for display
              id(meater_firmware).publish_state("v1.0.4_0");
              id(meater_device_name_display).publish_state("MEATER");
            } else {
              ESP_LOGE("meater", "✗ Failed to initialize BLE server");
            }
          }

# Generate mock temperature data and update BLE server
interval:
  - interval: 2s
    then:
      - lambda: |-
          // Generate mock temperature and battery data
          static uint32_t counter = 0;
          counter++;
          
          // Mock temperature data (8 bytes) - simulating slowly rising temperature
          // Format: tip_raw (2 bytes), ra (2 bytes), oa (2 bytes), max_temp (2 bytes)
          std::vector<uint8_t> temp_data(8);
          uint16_t base_temp = 300 + (counter % 200);  // Simulate 18-30°C range
          temp_data[0] = base_temp & 0xFF;
          temp_data[1] = (base_temp >> 8) & 0xFF;
          temp_data[2] = 100;  // ra
          temp_data[3] = 0;
          temp_data[4] = 80;   // oa
          temp_data[5] = 0;
          temp_data[6] = 0;    // max_temp
          temp_data[7] = 0;
          
          // Mock battery data (2 bytes) - simulating 90% battery
          std::vector<uint8_t> battery_data(2);
          battery_data[0] = 4;  // Battery data byte 1
          battery_data[1] = 5;  // Battery data byte 2 (4+5)*10 = 90%
          
          // Update BLE server with mock data
          if (id(ble_server_ptr) != nullptr) {
            ((MeaterBluedroidServer*)id(ble_server_ptr))->update_temperature(temp_data);
            ((MeaterBluedroidServer*)id(ble_server_ptr))->update_battery(battery_data);
          }
          
          // Update Home Assistant sensors with mock data
          uint16_t tip_temp = (temp_data[0] + (temp_data[1] << 8) + 8.0) / 16.0;
          id(meater_tip_temp).publish_state(tip_temp);
          
          uint16_t tip = temp_data[0] + (temp_data[1] << 8);
          uint16_t ra = temp_data[2] + (temp_data[3] << 8);
          uint16_t oa = temp_data[4] + (temp_data[5] << 8);
          uint16_t min_val = 48;
          uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
          id(meater_ambient_temp).publish_state(ambient);
          
          uint16_t battery = (battery_data[0] + battery_data[1]) * 10;
          id(meater_battery).publish_state(battery);
          
          // Mock RSSI
          id(meater_rssi).publish_state(-50.0);
 
text_sensor:
  - platform: template
    name: "MEATER firmware"
    id: meater_firmware
  - platform: template
    name: "MEATER device name"
    id: meater_device_name_display
 
# Template sensors for Home Assistant integration
# Real MEATER probe only does BLE - these sensors show what the probe is advertising
sensor:
  - platform: template
    name: "MEATER tip temperature"
    id: meater_tip_temp
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    
  - platform: template
    name: "MEATER ambient temperature"
    id: meater_ambient_temp
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    accuracy_decimals: 2
    
  - platform: template
    name: "MEATER battery level"
    id: meater_battery
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    accuracy_decimals: 0
    
  - platform: template
    name: "MEATER RSSI"
    id: meater_rssi
    unit_of_measurement: 'dBm'
    accuracy_decimals: 0
