"""
AI Recipe Builder Static Data

This file contains the static data for the AI Recipe Builder that can be
imported during frontend generation without requiring Home Assistant.
"""

# Cooking styles for AI recipe generation
COOKING_STYLES = [
    {"id": "quick_and_easy", "name": "Quick And Easy"},
    {"id": "comfort_food", "name": "Comfort Food"},
    {"id": "family_friendly", "name": "Family Friendly"},
    {"id": "healthy", "name": "Healthy"},
    {"id": "gourmet", "name": "Gourmet"},
    {"id": "meal_prep", "name": "Meal Prep"},
    {"id": "one_pot", "name": "One Pot"},
    {"id": "slow_cook", "name": "Slow Cook"},
    {"id": "barbeque", "name": "Barbeque"},
    {"id": "baking", "name": "Baking"},
    {"id": "low_carb", "name": "Low Carb"},
    {"id": "high_protein", "name": "High Protein"},
    {"id": "vegetarian", "name": "Vegetarian"},
    {"id": "vegan", "name": "Vegan"},
]

# Common ingredients grouped by category (default when no cuisine selected)
COMMON_INGREDIENTS = {
    "proteins": [
        {"id": "chicken_breast", "name": "Chicken Breast", "common": True},
        {"id": "chicken_thigh", "name": "Chicken Thighs", "common": True},
        {"id": "ground_beef", "name": "Ground Beef", "common": True},
        {"id": "steak", "name": "Steak (Beef)", "common": True},
        {"id": "pork_chop", "name": "Pork Chops", "common": True},
        {"id": "salmon", "name": "Salmon", "common": True},
        {"id": "shrimp", "name": "Shrimp", "common": True},
        {"id": "tofu", "name": "Tofu", "common": True},
        {"id": "eggs", "name": "Eggs", "common": True},
    ],
    "vegetables": [
        {"id": "broccoli", "name": "Broccoli", "common": True},
        {"id": "carrots", "name": "Carrots", "common": True},
        {"id": "bell_peppers", "name": "Bell Peppers", "common": True},
        {"id": "onions", "name": "Onions", "common": True},
        {"id": "garlic", "name": "Garlic", "common": True},
        {"id": "tomatoes", "name": "Tomatoes", "common": True},
        {"id": "spinach", "name": "Spinach", "common": True},
        {"id": "potatoes", "name": "Potatoes", "common": True},
        {"id": "sweet_potatoes", "name": "Sweet Potatoes", "common": True},
        {"id": "zucchini", "name": "Zucchini", "common": True},
        {"id": "cauliflower", "name": "Cauliflower", "common": True},
        {"id": "green_beans", "name": "Green Beans", "common": True},
    ],
    "grains": [
        {"id": "rice", "name": "Rice", "common": True},
        {"id": "pasta", "name": "Pasta", "common": True},
        {"id": "quinoa", "name": "Quinoa", "common": True},
        {"id": "bread", "name": "Bread", "common": True},
        {"id": "tortillas", "name": "Tortillas", "common": True},
    ],
    "dairy": [
        {"id": "cheese", "name": "Cheese", "common": True},
        {"id": "milk", "name": "Milk", "common": True},
        {"id": "butter", "name": "Butter", "common": True},
        {"id": "cream", "name": "Cream", "common": True},
        {"id": "yogurt", "name": "Yogurt", "common": True},
    ],
}

# ---------------------------------------------------------------------------
# Assumed staples — these are assumed to be available in every kitchen.
# They are NOT shown in the ingredient picker but are mentioned in the AI
# prompt so the AI knows it can use them.
# ---------------------------------------------------------------------------
ASSUMED_STAPLES = [
    "Cooking oil", "Butter", "Salt", "Black pepper", "Sugar", "Vinegar",
]

# ---------------------------------------------------------------------------
# Ingredient category mapping (used by frontend to group & sort ingredients).
#   p = Proteins   v = Produce   g = Grains & Starches
#   d = Dairy, Oils & Sauces     s = Spices, Nuts & Seasonings
# ---------------------------------------------------------------------------
INGREDIENT_CATEGORIES = {
    # Proteins
    "ackee": "p", "anchovies": "p", "andouille": "p", "bacon": "p",
    "beef": "p", "canned_tuna": "p", "catfish": "p", "chicken": "p",
    "chicken_breast": "p", "chicken_thigh": "p", "chorizo": "p",
    "chorizo_ar": "p", "cod": "p", "crab": "p", "crawfish": "p",
    "crayfish": "p", "dried_shrimp": "p", "duck": "p", "edamame": "p",
    "eggs": "p", "fish": "p", "goat": "p", "ground_beef": "p",
    "ham_hocks": "p", "herring": "p", "jamon": "p", "lamb": "p",
    "lamb_shank": "p", "lardons": "p", "meatball_mix": "p",
    "mussels": "p", "pancetta": "p", "paneer": "p", "pork": "p",
    "pork_belly": "p", "pork_chop": "p", "prosciutto": "p",
    "salmon": "p", "saltfish": "p", "sausage": "p", "shrimp": "p",
    "steak": "p", "stockfish": "p", "tempeh": "p", "tofu": "p",
    "tuna": "p",
    # Produce (vegetables, fruits, fresh herbs)
    "artichokes": "v", "avocado": "v", "bamboo_shoots": "v",
    "banana": "v", "banana_leaf": "v", "basil": "v", "basil_tw": "v",
    "bay_leaves": "v", "bean_sprouts": "v", "beetroot": "v", "beets": "v",
    "bell_peppers": "v", "bok_choy": "v", "breadfruit": "v",
    "broccoli": "v", "cabbage": "v", "calamansi": "v", "callaloo": "v",
    "carrots": "v", "cassava": "v", "cauliflower": "v", "celeriac": "v",
    "celery": "v", "chili": "v", "chinese_cabbage": "v", "chives": "v",
    "cilantro": "v", "collard_greens": "v", "corn": "v",
    "cucumber": "v", "curry_leaves": "v", "daikon": "v", "dill": "v",
    "eggplant": "v", "epazote": "v", "galangal": "v", "garlic": "v",
    "ginger": "v", "grape_leaves": "v", "green_beans": "v",
    "green_onions": "v", "green_papaya": "v", "herbs_mix": "v",
    "horseradish": "v", "jalapenos": "v", "kaffir_lime": "v",
    "korean_radish": "v", "leeks": "v", "lemon": "v", "lemongrass": "v",
    "lettuce": "v", "lime": "v", "mango": "v", "mint": "v",
    "morning_glory": "v", "mushrooms": "v", "napa_cabbage": "v",
    "okra": "v", "onions": "v", "oregano": "v", "pandan": "v",
    "papaya": "v", "parsley": "v", "parsnips": "v", "peas": "v",
    "perilla": "v", "pineapple": "v", "plantains": "v", "poblano": "v",
    "preserved_lemons": "v", "pumpkin": "v", "quince": "v",
    "radish": "v", "ridge_gourd": "v", "rosemary": "v",
    "san_marzano": "v", "scotch_bonnet": "v", "shallots": "v",
    "shiitake": "v", "spinach": "v", "spinach_ng": "v",
    "spring_onions": "v", "squash": "v", "sweet_potato": "v",
    "sweet_potatoes": "v", "tarragon": "v", "thai_basil": "v",
    "thai_chili": "v", "thyme": "v", "tomatillos": "v", "tomatoes": "v",
    "turnip": "v", "turnips": "v", "water_chestnuts": "v", "yam": "v",
    "yams": "v", "yuca": "v", "zucchini": "v",
    # Grains & Starches (incl. legumes, bread, noodles)
    "arborio_rice": "g", "baguette": "g", "barley": "g",
    "basmati_rice": "g", "beans": "g", "biscuit_dough": "g",
    "black_beans": "g", "black_eyed_peas": "g", "bread": "g",
    "bulgur": "g", "cannellini": "g", "chickpeas": "g",
    "ciabatta": "g", "corn_tortillas": "g", "cornbread": "g",
    "cornmeal": "g", "couscous": "g", "egg_noodles": "g",
    "empanada_dough": "g", "farofa": "g", "flat_bread": "g",
    "flour": "g", "flour_tortillas": "g", "freekeh": "g", "grits": "g",
    "injera_flour": "g", "japchae_noodles": "g", "jasmine_rice": "g",
    "kidney_beans": "g", "lavash": "g", "lentils": "g", "noodles": "g",
    "oats": "g", "panko": "g", "pasta": "g", "phyllo": "g", "pinto_beans": "g",
    "pita": "g", "potatoes": "g", "quinoa": "g", "red_beans": "g",
    "rice": "g", "rice_cakes": "g", "rice_noodles": "g",
    "rice_paper": "g", "rye_bread": "g", "soba": "g", "split_peas": "g",
    "taco_shells": "g", "tortillas": "g", "udon": "g",
    "wonton_wrappers": "g",
    # Dairy, Oils & Sauces
    "balsamic": "d", "bbq_sauce": "d", "black_vinegar": "d",
    "buttermilk": "d", "cheddar": "d", "cheese": "d", "chili_oil": "d",
    "chili_paste": "d", "coconut": "d", "coconut_milk": "d",
    "condensed_milk": "d", "cotija": "d", "cream": "d",
    "cream_cheese": "d", "creme_fraiche": "d", "dijon": "d",
    "doenjang": "d", "doubanjiang": "d", "dulce_de_leche": "d",
    "evaporated_milk": "d", "feta": "d", "fish_sauce": "d", "ghee": "d",
    "gochujang": "d", "green_curry_paste": "d", "gruyere": "d",
    "heavy_cream": "d", "herb_butter": "d", "hoisin_sauce": "d",
    "honey": "d", "hot_sauce": "d", "kecap_manis": "d", "kimchi": "d",
    "manchego": "d", "maple_syrup": "d", "milk": "d", "mirin": "d",
    "miso_paste": "d", "molasses": "d", "monterey_jack": "d",
    "mozzarella": "d", "mustard": "d", "niter_kibbeh": "d",
    "olive_oil": "d", "oyster_sauce": "d", "palm_oil": "d",
    "parmesan": "d", "pecorino": "d", "pomegranate_molasses": "d",
    "provolone": "d", "queso": "d", "queso_fresco": "d",
    "red_curry_paste": "d", "red_wine": "d", "red_wine_vinegar": "d",
    "refried_beans": "d", "rice_vinegar": "d", "rice_wine": "d",
    "ricotta": "d", "rose_water": "d", "rum": "d", "salsa": "d",
    "sesame_oil": "d", "sherry_vinegar": "d", "shrimp_paste": "d",
    "sour_cream": "d", "soy_sauce": "d", "sriracha": "d",
    "tahini": "d", "tamarind": "d", "tamarind_paste": "d",
    "tomato_paste": "d", "white_wine": "d", "wine_white": "d",
    "worcestershire": "d", "yogurt": "d",
    # Spices, Nuts & Seasonings
    "achiote": "s", "aji_amarillo": "s", "aji_panca": "s",
    "allspice": "s", "almonds": "s", "amchur": "s", "ancho": "s",
    "annatto": "s", "apricots": "s", "asafoetida": "s",
    "barberries": "s", "berbere": "s", "bonito": "s", "brown_sugar": "s",
    "cancha": "s", "candlenut": "s", "capers": "s", "cardamom": "s",
    "cayenne": "s", "chili_powder": "s", "chimichurri": "s",
    "chipotle": "s", "cinnamon": "s", "cloves": "s", "coriander": "s",
    "corn_starch": "s", "cumin": "s", "curry_powder": "s", "dates": "s",
    "dried_apricots": "s", "dried_limes": "s", "dried_mint": "s",
    "dried_seaweed": "s", "egusi": "s", "fenugreek": "s",
    "fermented_black_beans": "s", "file_powder": "s", "five_spice": "s",
    "garam_masala": "s", "gochugaru": "s", "hearts_of_palm": "s",
    "huacatay": "s", "jaggery": "s", "jollof_seasoning": "s",
    "juniper_berries": "s", "kokum": "s", "kombu": "s",
    "korerima": "s", "lingonberries": "s", "locust_beans": "s",
    "macadamia": "s", "mitmita": "s", "mustard_seeds": "s",
    "nigella_seeds": "s", "nori": "s", "nutmeg": "s", "olives": "s",
    "palm_sugar": "s", "paprika": "s", "peanuts": "s", "pecans": "s",
    "peppercorns": "s", "pickled_ginger": "s", "pine_nuts": "s",
    "pistachios": "s", "pomegranate": "s", "ras_el_hanout": "s",
    "red_pepper_flakes": "s", "rocoto": "s", "saffron": "s",
    "seaweed": "s", "sesame_seeds": "s", "sour_cherries": "s",
    "star_anise": "s", "sugar_cane": "s", "sumac": "s",
    "suya_spice": "s", "szechuan_pepper": "s", "turmeric": "s",
    "walnuts": "s", "wasabi": "s", "white_pepper": "s", "zaatar": "s",
}

# Category display labels (used by frontend for section headers)
CATEGORY_LABELS = {
    "p": "🥩 Proteins",
    "v": "🥬 Produce",
    "g": "🌾 Grains & Starches",
    "d": "🫙 Dairy, Oils & Sauces",
    "s": "🌶️ Spices, Nuts & Seasonings",
}

# Category display order
CATEGORY_ORDER = ["p", "v", "g", "d", "s"]

# ---------------------------------------------------------------------------
# Cuisine-specific ingredients
#
# Keys can be either a region ID or an individual cuisine ID.
# Lookup order: individual cuisine ID -> parent region ID -> COMMON_INGREDIENTS
#
# Staples (oil, butter, salt, pepper, sugar, vinegar) are assumed available
# and NOT listed — freeing slots for more distinctive ingredients & proteins.
# ---------------------------------------------------------------------------

def _ing(id_str, name):
    """Helper to create an ingredient dict."""
    return {"id": id_str, "name": name}

CUISINE_INGREDIENTS = {
    # ── Nordic & Scandinavian (region default) ──────────────────────────
    "nordic": [
        _ing("salmon", "Salmon"), _ing("cod", "Cod"), _ing("herring", "Herring"),
        _ing("potatoes", "Potatoes"), _ing("dill", "Dill"), _ing("cream", "Cream"),
        _ing("chicken", "Chicken"), _ing("rye_bread", "Rye Bread"),
        _ing("lingonberries", "Lingonberries"), _ing("beets", "Beets"),
        _ing("cabbage", "Cabbage"), _ing("pork", "Pork"), _ing("eggs", "Eggs"),
        _ing("onions", "Onions"), _ing("mushrooms", "Mushrooms"),
        _ing("sour_cream", "Sour Cream"), _ing("carrots", "Carrots"),
        _ing("parsnips", "Parsnips"), _ing("oats", "Oats"), _ing("barley", "Barley"),
        _ing("horseradish", "Horseradish"), _ing("cucumber", "Cucumber"),
        _ing("lamb", "Lamb"), _ing("turnips", "Turnips"), _ing("chives", "Chives"),
        _ing("celeriac", "Celeriac"), _ing("juniper_berries", "Juniper Berries"),
        _ing("cardamom", "Cardamom"),
    ],
    "swedish": [
        _ing("salmon", "Salmon"), _ing("potatoes", "Potatoes"), _ing("dill", "Dill"),
        _ing("cream", "Cream"), _ing("pork", "Pork"), _ing("lingonberries", "Lingonberries"),
        _ing("meatball_mix", "Ground Meat (Pork/Beef)"), _ing("herring", "Herring"),
        _ing("rye_bread", "Rye Bread (Knäckebröd)"), _ing("eggs", "Eggs"),
        _ing("onions", "Onions"), _ing("beets", "Beets"), _ing("cabbage", "Cabbage"),
        _ing("sour_cream", "Sour Cream"), _ing("mushrooms", "Mushrooms"),
        _ing("carrots", "Carrots"), _ing("peas", "Peas"), _ing("allspice", "Allspice"),
        _ing("white_pepper", "White Pepper"), _ing("chicken", "Chicken"),
        _ing("beef", "Beef"), _ing("cod", "Cod"), _ing("shrimp", "Shrimp"),
        _ing("oats", "Oats"), _ing("parsley", "Parsley"), _ing("horseradish", "Horseradish"),
        _ing("mustard", "Mustard"), _ing("anchovies", "Anchovies (Ansjovis)"),
    ],

    # ── East Asian (region default) ─────────────────────────────────────
    "east_asian": [
        _ing("rice", "Rice"), _ing("soy_sauce", "Soy Sauce"), _ing("ginger", "Ginger"),
        _ing("garlic", "Garlic"), _ing("green_onions", "Green Onions"),
        _ing("tofu", "Tofu"), _ing("sesame_oil", "Sesame Oil"),
        _ing("rice_vinegar", "Rice Vinegar"), _ing("chicken", "Chicken"),
        _ing("pork", "Pork"), _ing("shrimp", "Shrimp"), _ing("eggs", "Eggs"),
        _ing("mushrooms", "Mushrooms"), _ing("cabbage", "Cabbage"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("noodles", "Noodles"),
        _ing("miso_paste", "Miso Paste"), _ing("chili_paste", "Chili Paste"),
        _ing("bok_choy", "Bok Choy"), _ing("seaweed", "Seaweed"),
        _ing("corn_starch", "Corn Starch"), _ing("fish_sauce", "Fish Sauce"),
        _ing("beef", "Beef"), _ing("cilantro", "Cilantro"),
        _ing("radish", "Radish"), _ing("sweet_potato", "Sweet Potato"),
        _ing("sesame_seeds", "Sesame Seeds"), _ing("onions", "Onions"),
    ],
    "japanese": [
        _ing("rice", "Rice"), _ing("soy_sauce", "Soy Sauce"),
        _ing("miso_paste", "Miso Paste"), _ing("tofu", "Tofu"),
        _ing("salmon", "Salmon"), _ing("tuna", "Tuna"), _ing("shrimp", "Shrimp"),
        _ing("nori", "Nori (Seaweed)"), _ing("daikon", "Daikon Radish"),
        _ing("edamame", "Edamame"), _ing("shiitake", "Shiitake Mushrooms"),
        _ing("green_onions", "Green Onions"), _ing("ginger", "Ginger"),
        _ing("mirin", "Mirin"), _ing("rice_vinegar", "Rice Vinegar"),
        _ing("panko", "Panko Breadcrumbs"), _ing("sesame_oil", "Sesame Oil"),
        _ing("udon", "Udon Noodles"), _ing("soba", "Soba Noodles"),
        _ing("bonito", "Bonito Flakes"), _ing("kombu", "Kombu"),
        _ing("cabbage", "Cabbage"), _ing("eggs", "Eggs"),
        _ing("chicken_thigh", "Chicken Thighs"), _ing("pork_belly", "Pork Belly"),
        _ing("sweet_potato", "Sweet Potato"), _ing("pickled_ginger", "Pickled Ginger"),
        _ing("wasabi", "Wasabi"),
    ],
    # Chinese — authentic local Chinese pantry. Traditional techniques and
    # ingredients, not American-Chinese adaptations.
    "chinese": [
        _ing("rice", "Rice"), _ing("soy_sauce", "Soy Sauce (Light & Dark)"),
        _ing("ginger", "Ginger"), _ing("garlic", "Garlic"),
        _ing("green_onions", "Green Onions"), _ing("tofu", "Tofu"),
        _ing("bok_choy", "Bok Choy"), _ing("pork", "Pork"),
        _ing("chicken", "Chicken"), _ing("egg_noodles", "Egg Noodles"),
        _ing("sesame_oil", "Sesame Oil"), _ing("rice_wine", "Shaoxing Rice Wine"),
        _ing("doubanjiang", "Chili Bean Paste (Doubanjiang)"),
        _ing("oyster_sauce", "Oyster Sauce"),
        _ing("szechuan_pepper", "Szechuan Peppercorns"),
        _ing("star_anise", "Star Anise"), _ing("shiitake", "Shiitake Mushrooms"),
        _ing("chinese_cabbage", "Chinese Cabbage (Napa)"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("water_chestnuts", "Water Chestnuts"),
        _ing("bamboo_shoots", "Bamboo Shoots"), _ing("shrimp", "Shrimp"),
        _ing("duck", "Duck"), _ing("five_spice", "Five Spice Powder"),
        _ing("black_vinegar", "Chinkiang Black Vinegar"),
        _ing("fermented_black_beans", "Fermented Black Beans (Douchi)"),
        _ing("wonton_wrappers", "Wonton Wrappers"), _ing("eggs", "Eggs"),
    ],
    "korean": [
        _ing("rice", "Rice"), _ing("gochujang", "Gochujang (Chili Paste)"),
        _ing("gochugaru", "Gochugaru (Chili Flakes)"), _ing("soy_sauce", "Soy Sauce"),
        _ing("sesame_oil", "Sesame Oil"), _ing("garlic", "Garlic"),
        _ing("ginger", "Ginger"), _ing("green_onions", "Green Onions"),
        _ing("kimchi", "Kimchi"), _ing("tofu", "Tofu"),
        _ing("pork_belly", "Pork Belly"), _ing("beef", "Beef"),
        _ing("napa_cabbage", "Napa Cabbage"), _ing("bean_sprouts", "Bean Sprouts"),
        _ing("japchae_noodles", "Sweet Potato Noodles (Japchae)"),
        _ing("perilla", "Perilla Leaves"), _ing("dried_seaweed", "Dried Seaweed"),
        _ing("eggs", "Eggs"), _ing("zucchini", "Zucchini"),
        _ing("mushrooms", "Mushrooms"), _ing("doenjang", "Doenjang (Soybean Paste)"),
        _ing("sesame_seeds", "Sesame Seeds"), _ing("fish_sauce", "Fish Sauce"),
        _ing("rice_cakes", "Rice Cakes (Tteok)"), _ing("chicken", "Chicken"),
        _ing("spinach", "Spinach"), _ing("onions", "Onions"),
        _ing("korean_radish", "Korean Radish"),
    ],
    "taiwanese": [
        _ing("rice", "Rice"), _ing("soy_sauce", "Soy Sauce"),
        _ing("five_spice", "Five Spice Powder"), _ing("pork_belly", "Pork Belly"),
        _ing("chicken", "Chicken"), _ing("tofu", "Tofu"),
        _ing("sesame_oil", "Sesame Oil"), _ing("rice_wine", "Rice Wine"),
        _ing("garlic", "Garlic"), _ing("ginger", "Ginger"),
        _ing("green_onions", "Green Onions"), _ing("bok_choy", "Bok Choy"),
        _ing("noodles", "Noodles"), _ing("basil_tw", "Taiwanese Basil"),
        _ing("sweet_potato", "Sweet Potato"), _ing("bamboo_shoots", "Bamboo Shoots"),
        _ing("eggs", "Eggs"), _ing("mushrooms", "Mushrooms"),
        _ing("dried_shrimp", "Dried Shrimp"), _ing("chili_oil", "Chili Oil"),
        _ing("star_anise", "Star Anise"), _ing("oyster_sauce", "Oyster Sauce"),
        _ing("shrimp", "Shrimp"), _ing("cilantro", "Cilantro"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("corn_starch", "Corn Starch"),
        _ing("cabbage", "Cabbage"), _ing("turnip", "Daikon Radish"),
    ],

    # ── Southeast Asian (region default) ────────────────────────────────
    "southeast_asian": [
        _ing("jasmine_rice", "Jasmine Rice"), _ing("fish_sauce", "Fish Sauce"),
        _ing("coconut_milk", "Coconut Milk"), _ing("lemongrass", "Lemongrass"),
        _ing("garlic", "Garlic"), _ing("shallots", "Shallots"),
        _ing("ginger", "Ginger"), _ing("chili", "Chili"), _ing("lime", "Lime"),
        _ing("cilantro", "Cilantro"), _ing("shrimp", "Shrimp"),
        _ing("chicken", "Chicken"), _ing("tofu", "Tofu"),
        _ing("rice_noodles", "Rice Noodles"), _ing("bean_sprouts", "Bean Sprouts"),
        _ing("peanuts", "Peanuts"), _ing("palm_sugar", "Palm Sugar"),
        _ing("tamarind", "Tamarind"), _ing("basil", "Basil"),
        _ing("mint", "Mint"), _ing("eggplant", "Eggplant"),
        _ing("green_beans", "Green Beans"), _ing("bamboo_shoots", "Bamboo Shoots"),
        _ing("soy_sauce", "Soy Sauce"), _ing("turmeric", "Turmeric"),
        _ing("pork", "Pork"), _ing("mango", "Mango"), _ing("galangal", "Galangal"),
    ],
    "thai": [
        _ing("jasmine_rice", "Jasmine Rice"), _ing("fish_sauce", "Fish Sauce"),
        _ing("lemongrass", "Lemongrass"), _ing("galangal", "Galangal"),
        _ing("kaffir_lime", "Kaffir Lime Leaves"), _ing("thai_basil", "Thai Basil"),
        _ing("coconut_milk", "Coconut Milk"), _ing("thai_chili", "Thai Chili"),
        _ing("shrimp", "Shrimp"), _ing("chicken", "Chicken"), _ing("tofu", "Tofu"),
        _ing("rice_noodles", "Rice Noodles"), _ing("palm_sugar", "Palm Sugar"),
        _ing("tamarind_paste", "Tamarind Paste"), _ing("cilantro", "Cilantro"),
        _ing("garlic", "Garlic"), _ing("shallots", "Shallots"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("green_papaya", "Green Papaya"),
        _ing("peanuts", "Peanuts"), _ing("lime", "Lime"),
        _ing("eggplant", "Thai Eggplant"), _ing("morning_glory", "Morning Glory"),
        _ing("green_curry_paste", "Green Curry Paste"),
        _ing("red_curry_paste", "Red Curry Paste"), _ing("ginger", "Ginger"),
        _ing("bamboo_shoots", "Bamboo Shoots"), _ing("mango", "Mango"),
    ],
    "vietnamese": [
        _ing("rice_noodles", "Rice Noodles"), _ing("fish_sauce", "Fish Sauce"),
        _ing("rice_paper", "Rice Paper"), _ing("beef", "Beef"),
        _ing("lemongrass", "Lemongrass"), _ing("mint", "Mint"),
        _ing("cilantro", "Cilantro"), _ing("thai_basil", "Thai Basil"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("shrimp", "Shrimp"),
        _ing("pork", "Pork"), _ing("chicken", "Chicken"), _ing("tofu", "Tofu"),
        _ing("garlic", "Garlic"), _ing("shallots", "Shallots"),
        _ing("lime", "Lime"), _ing("chili", "Chili"),
        _ing("star_anise", "Star Anise"), _ing("cinnamon", "Cinnamon"),
        _ing("hoisin_sauce", "Hoisin Sauce"), _ing("sriracha", "Sriracha"),
        _ing("carrots", "Carrots"), _ing("daikon", "Daikon Radish"),
        _ing("lettuce", "Lettuce"), _ing("cucumber", "Cucumber"),
        _ing("green_onions", "Green Onions"), _ing("turmeric", "Turmeric"),
        _ing("coconut_milk", "Coconut Milk"),
    ],
    "indonesian": [
        _ing("rice", "Rice"), _ing("coconut_milk", "Coconut Milk"),
        _ing("shallots", "Shallots"), _ing("garlic", "Garlic"),
        _ing("galangal", "Galangal"), _ing("lemongrass", "Lemongrass"),
        _ing("turmeric", "Turmeric"), _ing("kaffir_lime", "Kaffir Lime Leaves"),
        _ing("chili", "Chili"), _ing("peanuts", "Peanuts"),
        _ing("kecap_manis", "Kecap Manis (Sweet Soy)"), _ing("tempeh", "Tempeh"),
        _ing("tofu", "Tofu"), _ing("chicken", "Chicken"), _ing("shrimp", "Shrimp"),
        _ing("eggs", "Eggs"), _ing("tamarind", "Tamarind"),
        _ing("palm_sugar", "Palm Sugar"), _ing("coriander", "Coriander"),
        _ing("cumin", "Cumin"), _ing("candlenut", "Candlenuts"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("green_beans", "Green Beans"),
        _ing("cabbage", "Cabbage"), _ing("lime", "Lime"),
        _ing("shrimp_paste", "Shrimp Paste (Terasi)"), _ing("noodles", "Egg Noodles"),
        _ing("banana_leaf", "Banana Leaf"),
    ],
    "malaysian": [
        _ing("rice", "Rice"), _ing("coconut_milk", "Coconut Milk"),
        _ing("lemongrass", "Lemongrass"), _ing("garlic", "Garlic"),
        _ing("shallots", "Shallots"), _ing("ginger", "Ginger"),
        _ing("turmeric", "Turmeric"), _ing("chili", "Chili"),
        _ing("shrimp_paste", "Shrimp Paste (Belacan)"), _ing("peanuts", "Peanuts"),
        _ing("chicken", "Chicken"), _ing("shrimp", "Shrimp"), _ing("tofu", "Tofu"),
        _ing("eggs", "Eggs"), _ing("rice_noodles", "Rice Noodles"),
        _ing("bean_sprouts", "Bean Sprouts"), _ing("tamarind", "Tamarind"),
        _ing("palm_sugar", "Palm Sugar"), _ing("kaffir_lime", "Kaffir Lime Leaves"),
        _ing("galangal", "Galangal"), _ing("soy_sauce", "Soy Sauce"),
        _ing("star_anise", "Star Anise"), _ing("cinnamon", "Cinnamon"),
        _ing("cardamom", "Cardamom"), _ing("cloves", "Cloves"),
        _ing("coriander", "Coriander"), _ing("cucumber", "Cucumber"),
        _ing("pandan", "Pandan Leaves"),
    ],
    "filipino": [
        _ing("rice", "Rice"), _ing("soy_sauce", "Soy Sauce"),
        _ing("pork_belly", "Pork Belly"), _ing("garlic", "Garlic"),
        _ing("onions", "Onions"), _ing("pork", "Pork"), _ing("chicken", "Chicken"),
        _ing("shrimp", "Shrimp"), _ing("fish_sauce", "Fish Sauce (Patis)"),
        _ing("coconut_milk", "Coconut Milk"), _ing("tomatoes", "Tomatoes"),
        _ing("calamansi", "Calamansi (Lime)"), _ing("bay_leaves", "Bay Leaves"),
        _ing("peppercorns", "Black Peppercorns"), _ing("eggs", "Eggs"),
        _ing("banana", "Banana (Saba)"), _ing("sweet_potato", "Sweet Potato"),
        _ing("eggplant", "Eggplant"), _ing("green_beans", "Green Beans"),
        _ing("tamarind", "Tamarind"), _ing("annatto", "Annatto Seeds"),
        _ing("lemongrass", "Lemongrass"), _ing("ginger", "Ginger"),
        _ing("chili", "Chili"), _ing("peanuts", "Peanuts"),
        _ing("noodles", "Rice Noodles"), _ing("cabbage", "Cabbage"),
        _ing("spring_onions", "Spring Onions"),
    ],

    # ── South Asian (region default) ────────────────────────────────────
    # Authentic subcontinental ingredients — no New World items (tomatoes,
    # chili powder) that dominate Americanized "Indian" recipes.
    # Sourness comes from tamarind, amchur, kokum — not tomato.
    "south_asian": [
        _ing("basmati_rice", "Basmati Rice"), _ing("chicken", "Chicken"),
        _ing("lamb", "Lamb"), _ing("lentils", "Lentils (Dal)"),
        _ing("chickpeas", "Chickpeas"), _ing("ghee", "Ghee"),
        _ing("cumin", "Cumin"), _ing("turmeric", "Turmeric"),
        _ing("coriander", "Coriander"), _ing("garam_masala", "Garam Masala"),
        _ing("tamarind", "Tamarind"), _ing("ginger", "Ginger"),
        _ing("garlic", "Garlic"), _ing("onions", "Onions"),
        _ing("curry_leaves", "Curry Leaves"), _ing("yogurt", "Yogurt"),
        _ing("paneer", "Paneer"), _ing("coconut", "Coconut (Fresh/Dried)"),
        _ing("spinach", "Spinach"), _ing("potatoes", "Potatoes"),
        _ing("cauliflower", "Cauliflower"), _ing("asafoetida", "Asafoetida (Hing)"),
        _ing("cardamom", "Cardamom"), _ing("cinnamon", "Cinnamon"),
        _ing("cloves", "Cloves"), _ing("fenugreek", "Fenugreek"),
        _ing("mustard_seeds", "Mustard Seeds"), _ing("goat", "Goat"),
    ],
    # Indian cuisine — authentic local tradition.
    # Traditional Indian cooking predates New World ingredients (tomatoes,
    # potatoes, chilies arrived only after 1500s Portuguese trade).
    # Sourness: tamarind, amchur, kokum, raw mango, yogurt.
    # Heat: black pepper, long pepper, green chili (adopted early).
    # Tomatoes are NOT included — they dominate Americanized Indian food
    # but are absent from most pre-colonial and many regional dishes.
    # Users wanting Indo-American fusion should select both cuisines.
    "indian": [
        _ing("basmati_rice", "Basmati Rice"), _ing("chicken", "Chicken"),
        _ing("lamb", "Lamb"), _ing("lentils", "Lentils (Dal)"),
        _ing("chickpeas", "Chickpeas"), _ing("ghee", "Ghee"),
        _ing("cumin", "Cumin"), _ing("turmeric", "Turmeric"),
        _ing("coriander", "Coriander"), _ing("garam_masala", "Garam Masala"),
        _ing("tamarind", "Tamarind"), _ing("ginger", "Ginger"),
        _ing("curry_leaves", "Curry Leaves"), _ing("onions", "Onions"),
        _ing("yogurt", "Yogurt"), _ing("paneer", "Paneer"),
        _ing("coconut", "Coconut (Fresh/Dried)"), _ing("mustard_seeds", "Mustard Seeds"),
        _ing("asafoetida", "Asafoetida (Hing)"), _ing("amchur", "Amchur (Dried Mango Powder)"),
        _ing("kokum", "Kokum"), _ing("jaggery", "Jaggery"),
        _ing("fenugreek", "Fenugreek (Methi)"), _ing("cardamom", "Cardamom"),
        _ing("cinnamon", "Cinnamon"), _ing("cloves", "Cloves"),
        _ing("goat", "Goat"), _ing("ridge_gourd", "Ridge Gourd / Drumstick"),
    ],

    # ── Middle Eastern (region default) ─────────────────────────────────
    # Authentic Levantine / Fertile Crescent pantry.
    # Tomatoes and bell peppers are post-Columbian; replaced with
    # traditional souring/flavouring: pomegranate molasses, sumac, dried limes.
    "middle_east": [
        _ing("chickpeas", "Chickpeas"), _ing("tahini", "Tahini"),
        _ing("olive_oil", "Olive Oil"), _ing("lemon", "Lemon"),
        _ing("garlic", "Garlic"), _ing("lamb", "Lamb"), _ing("chicken", "Chicken"),
        _ing("rice", "Rice"), _ing("pita", "Pita Bread"),
        _ing("pomegranate", "Pomegranate"), _ing("sumac", "Sumac"),
        _ing("zaatar", "Za'atar"), _ing("cumin", "Cumin"),
        _ing("coriander", "Coriander"), _ing("parsley", "Parsley"),
        _ing("mint", "Mint"), _ing("dried_limes", "Dried Limes (Loomi)"),
        _ing("cucumber", "Cucumber"), _ing("onions", "Onions"),
        _ing("eggplant", "Eggplant"), _ing("yogurt", "Yogurt"),
        _ing("bulgur", "Bulgur Wheat"), _ing("pine_nuts", "Pine Nuts"),
        _ing("saffron", "Saffron"), _ing("beef", "Beef"),
        _ing("dates", "Dates"), _ing("pomegranate_molasses", "Pomegranate Molasses"),
        _ing("fish", "Fish"),
    ],
    # Turkish — authentic Anatolian tradition; no New World tomatoes/peppers.
    "turkish": [
        _ing("lamb", "Lamb"), _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("yogurt", "Yogurt"), _ing("eggplant", "Eggplant"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("olive_oil", "Olive Oil"), _ing("bulgur", "Bulgur"),
        _ing("lentils", "Lentils"), _ing("chickpeas", "Chickpeas"),
        _ing("rice", "Rice"), _ing("pita", "Pita Bread"),
        _ing("feta", "White Cheese (Beyaz Peynir)"), _ing("parsley", "Parsley"),
        _ing("mint", "Mint"), _ing("dill", "Dill"), _ing("sumac", "Sumac"),
        _ing("cumin", "Cumin"), _ing("dried_mint", "Dried Mint (Nane)"),
        _ing("pomegranate_molasses", "Pomegranate Molasses"),
        _ing("walnuts", "Walnuts"), _ing("pine_nuts", "Pine Nuts"),
        _ing("dried_apricots", "Dried Apricots"), _ing("phyllo", "Phyllo Dough"),
        _ing("fish", "Fish"), _ing("grape_leaves", "Grape Leaves"),
        _ing("shrimp", "Shrimp"),
    ],
    # Persian / Iranian — ancient culinary tradition predating New World contact.
    # Uses dried limes, sour cherries, pomegranate, barberries for tartness.
    "persian": [
        _ing("basmati_rice", "Basmati Rice"), _ing("saffron", "Saffron"),
        _ing("lamb", "Lamb"), _ing("chicken", "Chicken"),
        _ing("barberries", "Barberries (Zereshk)"), _ing("pomegranate", "Pomegranate"),
        _ing("walnuts", "Walnuts"), _ing("pistachios", "Pistachios"),
        _ing("dried_limes", "Dried Limes (Limoo Amani)"),
        _ing("turmeric", "Turmeric"), _ing("rose_water", "Rose Water"),
        _ing("yogurt", "Yogurt"), _ing("eggplant", "Eggplant"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("herbs_mix", "Fresh Herbs (Parsley, Dill, Cilantro)"),
        _ing("fenugreek", "Fenugreek"), _ing("split_peas", "Split Peas"),
        _ing("kidney_beans", "Kidney Beans"), _ing("lamb_shank", "Lamb Shank"),
        _ing("sour_cherries", "Sour Cherries"), _ing("sumac", "Sumac"),
        _ing("lavash", "Lavash Bread"), _ing("fish", "Fish (Mahi)"),
        _ing("cinnamon", "Cinnamon"), _ing("cardamom", "Cardamom"),
        _ing("dried_apricots", "Dried Apricots"), _ing("quince", "Quince"),
    ],
    # Lebanese — authentic Levantine tradition.
    "lebanese": [
        _ing("chickpeas", "Chickpeas"), _ing("tahini", "Tahini"),
        _ing("olive_oil", "Olive Oil"), _ing("lemon", "Lemon"),
        _ing("garlic", "Garlic"), _ing("lamb", "Lamb"), _ing("chicken", "Chicken"),
        _ing("rice", "Rice"), _ing("pita", "Pita Bread"),
        _ing("pomegranate", "Pomegranate"), _ing("sumac", "Sumac"),
        _ing("zaatar", "Za'atar"), _ing("cumin", "Cumin"),
        _ing("parsley", "Flat-Leaf Parsley"), _ing("mint", "Mint"),
        _ing("cucumber", "Cucumber"), _ing("eggplant", "Eggplant"),
        _ing("onions", "Onions"), _ing("yogurt", "Yogurt"),
        _ing("bulgur", "Bulgur Wheat (#1 Fine)"),
        _ing("pine_nuts", "Pine Nuts"), _ing("allspice", "Allspice"),
        _ing("cinnamon", "Cinnamon"), _ing("grape_leaves", "Grape Leaves"),
        _ing("pomegranate_molasses", "Pomegranate Molasses"),
        _ing("fish", "Fish"), _ing("freekeh", "Freekeh"),
        _ing("beef", "Beef"),
    ],

    # ── European (region default) ───────────────────────────────────────
    "european": [
        _ing("olive_oil", "Olive Oil"), _ing("lamb", "Lamb"),
        _ing("garlic", "Garlic"), _ing("onions", "Onions"),
        _ing("tomatoes", "Tomatoes"), _ing("potatoes", "Potatoes"),
        _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("pork", "Pork"), _ing("eggs", "Eggs"), _ing("cream", "Cream"),
        _ing("cheese", "Cheese"), _ing("mushrooms", "Mushrooms"),
        _ing("bell_peppers", "Bell Peppers"), _ing("carrots", "Carrots"),
        _ing("celery", "Celery"), _ing("wine_white", "White Wine"),
        _ing("parsley", "Parsley"), _ing("thyme", "Thyme"),
        _ing("rosemary", "Rosemary"), _ing("bread", "Bread"),
        _ing("pasta", "Pasta"), _ing("rice", "Rice"),
        _ing("leeks", "Leeks"), _ing("spinach", "Spinach"),
        _ing("zucchini", "Zucchini"), _ing("flour", "Flour"),
        _ing("bay_leaves", "Bay Leaves"),
    ],
    "italian": [
        _ing("pasta", "Pasta"), _ing("olive_oil", "Olive Oil"),
        _ing("garlic", "Garlic"), _ing("san_marzano", "San Marzano Tomatoes"),
        _ing("basil", "Fresh Basil"), _ing("parmesan", "Parmesan Cheese"),
        _ing("mozzarella", "Mozzarella"), _ing("prosciutto", "Prosciutto"),
        _ing("pancetta", "Pancetta"), _ing("onions", "Onions"),
        _ing("zucchini", "Zucchini"), _ing("eggplant", "Eggplant"),
        _ing("bell_peppers", "Bell Peppers"), _ing("arborio_rice", "Arborio Rice"),
        _ing("white_wine", "White Wine"), _ing("chicken", "Chicken"),
        _ing("capers", "Capers"), _ing("olives", "Olives"),
        _ing("pine_nuts", "Pine Nuts"), _ing("ricotta", "Ricotta"),
        _ing("beef", "Beef"),
        _ing("oregano", "Oregano"), _ing("rosemary", "Rosemary"),
        _ing("anchovies", "Anchovies"), _ing("shrimp", "Shrimp"),
        _ing("pork", "Pork"), _ing("pecorino", "Pecorino Romano"),
        _ing("cannellini", "Cannellini Beans"),
    ],
    "french": [
        _ing("lamb", "Lamb"), _ing("shallots", "Shallots"),
        _ing("garlic", "Garlic"), _ing("white_wine", "White Wine"),
        _ing("heavy_cream", "Heavy Cream"), _ing("dijon", "Dijon Mustard"),
        _ing("thyme", "Thyme"), _ing("tarragon", "Tarragon"),
        _ing("parsley", "Parsley"), _ing("chicken", "Chicken"),
        _ing("duck", "Duck"), _ing("beef", "Beef"),
        _ing("potatoes", "Potatoes"), _ing("leeks", "Leeks"),
        _ing("mushrooms", "Mushrooms"), _ing("gruyere", "Gruyère Cheese"),
        _ing("creme_fraiche", "Crème Fraîche"), _ing("flour", "Flour"),
        _ing("eggs", "Eggs"), _ing("baguette", "Baguette"),
        _ing("olive_oil", "Olive Oil"), _ing("carrots", "Carrots"),
        _ing("celery", "Celery"), _ing("bay_leaves", "Bay Leaves"),
        _ing("tomato_paste", "Tomato Paste"), _ing("lardons", "Lardons (Bacon)"),
        _ing("herb_butter", "Herb Butter"), _ing("onions", "Onions"),
    ],
    "spanish": [
        _ing("olive_oil", "Olive Oil"), _ing("garlic", "Garlic"),
        _ing("onions", "Onions"), _ing("tomatoes", "Tomatoes"),
        _ing("bell_peppers", "Bell Peppers (Pimientos)"),
        _ing("chorizo", "Chorizo"), _ing("jamon", "Jamón Serrano"),
        _ing("saffron", "Saffron"), _ing("paprika", "Smoked Paprika (Pimentón)"),
        _ing("rice", "Bomba/Calasparra Rice"), _ing("shrimp", "Shrimp"),
        _ing("mussels", "Mussels"), _ing("chicken", "Chicken"),
        _ing("pork", "Pork"), _ing("eggs", "Eggs"),
        _ing("potatoes", "Potatoes"), _ing("manchego", "Manchego Cheese"),
        _ing("wine_white", "White Wine"), _ing("sherry_vinegar", "Sherry Vinegar"),
        _ing("parsley", "Parsley"), _ing("bay_leaves", "Bay Leaves"),
        _ing("almonds", "Almonds"), _ing("chickpeas", "Chickpeas"),
        _ing("green_beans", "Green Beans"), _ing("artichokes", "Artichokes"),
        _ing("bread", "Bread"), _ing("lemon", "Lemon"),
        _ing("canned_tuna", "Canned Tuna"),
    ],
    "greek": [
        _ing("olive_oil", "Olive Oil"), _ing("lemon", "Lemon"),
        _ing("garlic", "Garlic"), _ing("onions", "Onions"),
        _ing("tomatoes", "Tomatoes"), _ing("cucumber", "Cucumber"),
        _ing("feta", "Feta Cheese"), _ing("oregano", "Oregano"),
        _ing("lamb", "Lamb"), _ing("chicken", "Chicken"),
        _ing("yogurt", "Greek Yogurt"), _ing("eggplant", "Eggplant"),
        _ing("zucchini", "Zucchini"), _ing("bell_peppers", "Bell Peppers"),
        _ing("olives", "Kalamata Olives"), _ing("phyllo", "Phyllo Dough"),
        _ing("spinach", "Spinach"), _ing("rice", "Rice"),
        _ing("potatoes", "Potatoes"), _ing("dill", "Dill"),
        _ing("parsley", "Parsley"), _ing("mint", "Mint"),
        _ing("pork", "Pork"), _ing("shrimp", "Shrimp"),
        _ing("bread", "Pita Bread"), _ing("pine_nuts", "Pine Nuts"),
        _ing("capers", "Capers"), _ing("white_wine", "White Wine"),
    ],

    # ── North American (region default) ─────────────────────────────────
    "north_american": [
        _ing("ground_beef", "Ground Beef"), _ing("chicken_breast", "Chicken Breast"),
        _ing("potatoes", "Potatoes"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("cheddar", "Cheddar Cheese"),
        _ing("bacon", "Bacon"), _ing("pork", "Pork"), _ing("eggs", "Eggs"),
        _ing("corn", "Corn"), _ing("lettuce", "Lettuce"),
        _ing("tomatoes", "Tomatoes"), _ing("bell_peppers", "Bell Peppers"),
        _ing("bbq_sauce", "BBQ Sauce"), _ing("mustard", "Mustard"),
        _ing("flour", "Flour"), _ing("milk", "Milk"), _ing("bread", "Bread"),
        _ing("sausage", "Sausage"), _ing("sour_cream", "Sour Cream"),
        _ing("sweet_potatoes", "Sweet Potatoes"), _ing("green_beans", "Green Beans"),
        _ing("cream_cheese", "Cream Cheese"), _ing("maple_syrup", "Maple Syrup"),
        _ing("pecans", "Pecans"), _ing("cornbread", "Cornbread"),
        _ing("rice", "Rice"), _ing("mushrooms", "Mushrooms"),
    ],
    "american": [
        _ing("ground_beef", "Ground Beef"), _ing("chicken_breast", "Chicken Breast"),
        _ing("potatoes", "Potatoes"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("cheddar", "Cheddar Cheese"),
        _ing("bacon", "Bacon"), _ing("pork", "Pork"), _ing("eggs", "Eggs"),
        _ing("corn", "Corn"), _ing("lettuce", "Lettuce"),
        _ing("tomatoes", "Tomatoes"), _ing("bell_peppers", "Bell Peppers"),
        _ing("bbq_sauce", "BBQ Sauce"), _ing("mustard", "Mustard"),
        _ing("flour", "All-Purpose Flour"), _ing("milk", "Milk"),
        _ing("bread", "Bread"), _ing("sausage", "Sausage"),
        _ing("sour_cream", "Sour Cream"), _ing("sweet_potatoes", "Sweet Potatoes"),
        _ing("green_beans", "Green Beans"), _ing("cream_cheese", "Cream Cheese"),
        _ing("maple_syrup", "Maple Syrup"), _ing("pecans", "Pecans"),
        _ing("cornbread", "Cornbread"), _ing("rice", "Rice"),
        _ing("mushrooms", "Mushrooms"),
    ],
    "cajun_creole": [
        _ing("rice", "Rice"), _ing("shrimp", "Shrimp"), _ing("crawfish", "Crawfish"),
        _ing("andouille", "Andouille Sausage"), _ing("chicken", "Chicken"),
        _ing("onions", "Onions"), _ing("celery", "Celery"),
        _ing("bell_peppers", "Bell Peppers (Holy Trinity)"),
        _ing("garlic", "Garlic"), _ing("cayenne", "Cayenne Pepper"),
        _ing("paprika", "Paprika"), _ing("thyme", "Thyme"),
        _ing("bay_leaves", "Bay Leaves"), _ing("okra", "Okra"),
        _ing("tomatoes", "Tomatoes"), _ing("file_powder", "Filé Powder"),
        _ing("duck", "Duck"), _ing("flour", "Flour"),
        _ing("green_onions", "Green Onions"), _ing("hot_sauce", "Hot Sauce"),
        _ing("worcestershire", "Worcestershire Sauce"),
        _ing("crab", "Crab"), _ing("corn", "Corn"), _ing("pork", "Pork"),
        _ing("black_eyed_peas", "Black-Eyed Peas"),
        _ing("red_beans", "Red Kidney Beans"), _ing("catfish", "Catfish"),
        _ing("parsley", "Parsley"),
    ],
    "tex_mex": [
        _ing("ground_beef", "Ground Beef"), _ing("chicken", "Chicken"),
        _ing("tortillas", "Flour Tortillas"), _ing("corn_tortillas", "Corn Tortillas"),
        _ing("cheddar", "Cheddar Cheese"), _ing("monterey_jack", "Monterey Jack"),
        _ing("refried_beans", "Refried Beans"), _ing("rice", "Rice"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("tomatoes", "Tomatoes"), _ing("jalapenos", "Jalapeños"),
        _ing("cumin", "Cumin"), _ing("chili_powder", "Chili Powder"),
        _ing("sour_cream", "Sour Cream"), _ing("avocado", "Avocado"),
        _ing("lime", "Lime"), _ing("cilantro", "Cilantro"),
        _ing("corn", "Corn"), _ing("black_beans", "Black Beans"),
        _ing("bell_peppers", "Bell Peppers"), _ing("salsa", "Salsa"),
        _ing("queso", "Queso (Nacho Cheese)"), _ing("lettuce", "Lettuce"),
        _ing("hot_sauce", "Hot Sauce"), _ing("sausage", "Chorizo"),
        _ing("pork", "Pork"), _ing("shrimp", "Shrimp"),
    ],
    "southern_us": [
        _ing("chicken", "Chicken"), _ing("pork", "Pork"),
        _ing("bacon", "Bacon"), _ing("turkey", "Turkey"),
        _ing("buttermilk", "Buttermilk"), _ing("cornmeal", "Cornmeal"),
        _ing("flour", "All-Purpose Flour"), _ing("grits", "Grits"),
        _ing("collard_greens", "Collard Greens"), _ing("sweet_potatoes", "Sweet Potatoes"),
        _ing("corn", "Corn"), _ing("okra", "Okra"),
        _ing("tomatoes", "Tomatoes"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("green_beans", "Green Beans"),
        _ing("black_eyed_peas", "Black-Eyed Peas"), _ing("rice", "Rice"),
        _ing("hot_sauce", "Hot Sauce"), _ing("pecans", "Pecans"),
        _ing("eggs", "Eggs"), _ing("biscuit_dough", "Biscuit Dough"),
        _ing("cheddar", "Cheddar Cheese"), _ing("cream", "Cream"),
        _ing("catfish", "Catfish"), _ing("shrimp", "Shrimp"),
        _ing("ham_hocks", "Ham Hocks"), _ing("molasses", "Molasses"),
    ],

    # ── Latin American (region default) ─────────────────────────────────
    "latin_american": [
        _ing("rice", "Rice"), _ing("black_beans", "Black Beans"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("tomatoes", "Tomatoes"), _ing("cilantro", "Cilantro"),
        _ing("lime", "Lime"), _ing("avocado", "Avocado"),
        _ing("corn", "Corn"), _ing("chili", "Chili Peppers"),
        _ing("cumin", "Cumin"), _ing("chicken", "Chicken"),
        _ing("pork", "Pork"), _ing("beef", "Beef"), _ing("eggs", "Eggs"),
        _ing("bell_peppers", "Bell Peppers"), _ing("plantains", "Plantains"),
        _ing("yuca", "Yuca (Cassava)"), _ing("potatoes", "Potatoes"),
        _ing("oregano", "Oregano"), _ing("corn_tortillas", "Corn Tortillas"),
        _ing("queso_fresco", "Queso Fresco"), _ing("sour_cream", "Sour Cream"),
        _ing("olive_oil", "Olive Oil"), _ing("coconut_milk", "Coconut Milk"),
        _ing("achiote", "Achiote (Annatto)"), _ing("pinto_beans", "Pinto Beans"),
        _ing("shrimp", "Shrimp"),
    ],
    "mexican": [
        _ing("corn_tortillas", "Corn Tortillas"), _ing("avocado", "Avocado"),
        _ing("lime", "Lime"), _ing("cilantro", "Cilantro"),
        _ing("jalapenos", "Jalapeños"), _ing("tomatoes", "Tomatoes"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("cumin", "Cumin"), _ing("chili_powder", "Chili Powder"),
        _ing("black_beans", "Black Beans"), _ing("pinto_beans", "Pinto Beans"),
        _ing("rice", "Rice"), _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("pork", "Pork (Carnitas)"), _ing("cotija", "Cotija Cheese"),
        _ing("sour_cream", "Crema (Sour Cream)"),
        _ing("chipotle", "Chipotle Peppers (in Adobo)"), _ing("corn", "Corn"),
        _ing("poblano", "Poblano Peppers"), _ing("tomatillos", "Tomatillos"),
        _ing("oregano", "Mexican Oregano"), _ing("epazote", "Epazote"),
        _ing("queso_fresco", "Queso Fresco"),
        _ing("shrimp", "Shrimp"),
        _ing("cinnamon", "Cinnamon (Canela)"), _ing("ancho", "Ancho Chili"),
    ],
    "brazilian": [
        _ing("rice", "Rice"), _ing("black_beans", "Black Beans (Feijão)"),
        _ing("farofa", "Farofa (Toasted Cassava Flour)"), _ing("beef", "Beef"),
        _ing("chicken", "Chicken"), _ing("pork", "Pork"),
        _ing("sausage", "Linguiça Sausage"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("tomatoes", "Tomatoes"),
        _ing("bell_peppers", "Bell Peppers"), _ing("coconut_milk", "Coconut Milk"),
        _ing("palm_oil", "Dendê (Palm Oil)"), _ing("lime", "Lime"),
        _ing("cilantro", "Cilantro"), _ing("bay_leaves", "Bay Leaves"),
        _ing("eggs", "Eggs"), _ing("cassava", "Cassava (Yuca)"),
        _ing("plantains", "Plantains"), _ing("shrimp", "Shrimp"),
        _ing("hearts_of_palm", "Hearts of Palm"), _ing("corn", "Corn"),
        _ing("cheese", "Queijo Minas (Cheese)"), _ing("condensed_milk", "Condensed Milk"),
        _ing("collard_greens", "Collard Greens (Couve)"),
        _ing("potatoes", "Potatoes"), _ing("okra", "Okra"),
    ],
    "peruvian": [
        _ing("potatoes", "Potatoes"), _ing("rice", "Rice"),
        _ing("aji_amarillo", "Ají Amarillo (Yellow Chili)"),
        _ing("lime", "Lime"), _ing("garlic", "Garlic"),
        _ing("onions", "Red Onions"), _ing("cilantro", "Cilantro"),
        _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("shrimp", "Shrimp"), _ing("fish", "White Fish"),
        _ing("corn", "Giant Corn (Choclo)"), _ing("sweet_potato", "Sweet Potato"),
        _ing("quinoa", "Quinoa"), _ing("aji_panca", "Ají Panca"),
        _ing("cumin", "Cumin"), _ing("soy_sauce", "Soy Sauce"),
        _ing("huacatay", "Huacatay (Black Mint)"),
        _ing("evaporated_milk", "Evaporated Milk"), _ing("eggs", "Eggs"),
        _ing("olives", "Black Olives"), _ing("lettuce", "Lettuce"),
        _ing("tomatoes", "Tomatoes"), _ing("avocado", "Avocado"),
        _ing("rocoto", "Rocoto Pepper"), _ing("peanuts", "Peanuts"),
        _ing("cancha", "Cancha (Toasted Corn)"), _ing("oregano", "Oregano"),
    ],
    "argentinian": [
        _ing("beef", "Beef (Asado cuts)"), _ing("chimichurri", "Chimichurri herbs"),
        _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("bell_peppers", "Bell Peppers"), _ing("tomatoes", "Tomatoes"),
        _ing("olive_oil", "Olive Oil"), _ing("red_wine_vinegar", "Red Wine Vinegar"),
        _ing("oregano", "Oregano"), _ing("parsley", "Parsley"),
        _ing("eggs", "Eggs"), _ing("potatoes", "Potatoes"),
        _ing("corn", "Corn"), _ing("squash", "Butternut Squash"),
        _ing("empanada_dough", "Empanada Dough"), _ing("chorizo_ar", "Chorizo"),
        _ing("mozzarella", "Mozzarella"), _ing("provolone", "Provoleta Cheese"),
        _ing("flour", "Flour"), _ing("dulce_de_leche", "Dulce de Leche"),
        _ing("chicken", "Chicken"), _ing("pork", "Pork"),
        _ing("red_wine", "Red Wine (Malbec)"), _ing("cumin", "Cumin"),
        _ing("paprika", "Paprika"), _ing("bay_leaves", "Bay Leaves"),
        _ing("spinach", "Spinach"), _ing("olives", "Green Olives"),
    ],

    # ── Caribbean (region default) ──────────────────────────────────────
    "caribbean_region": [
        _ing("rice", "Rice"), _ing("beans", "Kidney Beans"),
        _ing("chicken", "Chicken"), _ing("pork", "Pork"),
        _ing("fish", "Fish"), _ing("shrimp", "Shrimp"),
        _ing("coconut_milk", "Coconut Milk"), _ing("plantains", "Plantains"),
        _ing("scotch_bonnet", "Scotch Bonnet Pepper"),
        _ing("thyme", "Thyme"), _ing("allspice", "Allspice"),
        _ing("garlic", "Garlic"), _ing("onions", "Onions"),
        _ing("ginger", "Ginger"), _ing("lime", "Lime"),
        _ing("tomatoes", "Tomatoes"), _ing("bell_peppers", "Bell Peppers"),
        _ing("sweet_potato", "Sweet Potato"), _ing("yuca", "Yuca (Cassava)"),
        _ing("cilantro", "Cilantro"), _ing("cumin", "Cumin"),
        _ing("corn", "Corn"), _ing("avocado", "Avocado"),
        _ing("mango", "Mango"), _ing("papaya", "Papaya"),
        _ing("rum", "Rum"), _ing("sugar_cane", "Brown Sugar"),
        _ing("green_onions", "Green Onions"),
    ],
    "jamaican": [
        _ing("chicken", "Chicken"), _ing("pork", "Pork"),
        _ing("goat", "Goat"), _ing("scotch_bonnet", "Scotch Bonnet Pepper"),
        _ing("allspice", "Allspice (Pimento)"), _ing("thyme", "Thyme"),
        _ing("garlic", "Garlic"), _ing("ginger", "Ginger"),
        _ing("green_onions", "Green Onions (Scallion)"),
        _ing("soy_sauce", "Soy Sauce"), _ing("rice", "Rice"),
        _ing("kidney_beans", "Kidney Beans"), _ing("coconut_milk", "Coconut Milk"),
        _ing("plantains", "Plantains"), _ing("ackee", "Ackee"),
        _ing("saltfish", "Salt Cod (Saltfish)"), _ing("yam", "Yam"),
        _ing("sweet_potato", "Sweet Potato"), _ing("callaloo", "Callaloo"),
        _ing("breadfruit", "Breadfruit"), _ing("lime", "Lime"),
        _ing("tomatoes", "Tomatoes"), _ing("onions", "Onions"),
        _ing("bell_peppers", "Bell Peppers"), _ing("corn", "Corn"),
        _ing("brown_sugar", "Brown Sugar"), _ing("nutmeg", "Nutmeg"),
        _ing("cinnamon", "Cinnamon"),
    ],

    # ── African (region default) ────────────────────────────────────────
    "african": [
        _ing("rice", "Rice"), _ing("onions", "Onions"), _ing("garlic", "Garlic"),
        _ing("ginger", "Ginger"), _ing("tomatoes", "Tomatoes"),
        _ing("chili", "Chili Peppers"), _ing("chicken", "Chicken"),
        _ing("beef", "Beef"), _ing("lamb", "Lamb"), _ing("fish", "Fish"),
        _ing("peanuts", "Peanuts (Groundnuts)"), _ing("okra", "Okra"),
        _ing("sweet_potato", "Sweet Potato"), _ing("yams", "Yams"),
        _ing("plantains", "Plantains"), _ing("cassava", "Cassava"),
        _ing("black_eyed_peas", "Black-Eyed Peas"), _ing("lentils", "Lentils"),
        _ing("coconut_milk", "Coconut Milk"), _ing("palm_oil", "Palm Oil"),
        _ing("coriander", "Coriander"), _ing("cumin", "Cumin"),
        _ing("turmeric", "Turmeric"), _ing("cinnamon", "Cinnamon"),
        _ing("cilantro", "Cilantro"), _ing("spinach", "Spinach"),
        _ing("corn", "Corn (Maize)"), _ing("bell_peppers", "Bell Peppers"),
    ],
    "ethiopian": [
        _ing("injera_flour", "Teff Flour (for Injera)"), _ing("berbere", "Berbere Spice"),
        _ing("niter_kibbeh", "Niter Kibbeh (Spiced Butter)"),
        _ing("onions", "Red Onions"), _ing("garlic", "Garlic"),
        _ing("ginger", "Ginger"), _ing("tomatoes", "Tomatoes"),
        _ing("chicken", "Chicken"), _ing("beef", "Beef"), _ing("lamb", "Lamb"),
        _ing("lentils", "Red Lentils (Misir)"), _ing("split_peas", "Yellow Split Peas"),
        _ing("chickpeas", "Chickpeas"), _ing("collard_greens", "Collard Greens (Gomen)"),
        _ing("cabbage", "Cabbage"), _ing("carrots", "Carrots"),
        _ing("potatoes", "Potatoes"), _ing("green_beans", "Green Beans"),
        _ing("eggs", "Eggs"), _ing("turmeric", "Turmeric"),
        _ing("fenugreek", "Fenugreek"), _ing("cardamom", "Cardamom"),
        _ing("coriander", "Coriander"), _ing("cumin", "Cumin"),
        _ing("chili", "Chili Peppers"), _ing("mitmita", "Mitmita Spice"),
        _ing("korerima", "Korerima (Ethiopian Cardamom)"),
        _ing("nigella_seeds", "Nigella Seeds"),
    ],
    "moroccan": [
        _ing("lamb", "Lamb"), _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("couscous", "Couscous"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("ginger", "Ginger"),
        _ing("saffron", "Saffron"), _ing("cumin", "Cumin"),
        _ing("coriander", "Coriander"), _ing("cinnamon", "Cinnamon"),
        _ing("turmeric", "Turmeric"), _ing("paprika", "Paprika"),
        _ing("ras_el_hanout", "Ras el Hanout"), _ing("preserved_lemons", "Preserved Lemons"),
        _ing("olives", "Olives"), _ing("almonds", "Almonds"),
        _ing("dates", "Dates"), _ing("apricots", "Dried Apricots"),
        _ing("honey", "Honey"), _ing("tomatoes", "Tomatoes"),
        _ing("chickpeas", "Chickpeas"), _ing("lentils", "Lentils"),
        _ing("carrots", "Carrots"), _ing("zucchini", "Zucchini"),
        _ing("turnips", "Turnips"), _ing("cilantro", "Cilantro"),
        _ing("fish", "Fish"),
    ],
    "nigerian": [
        _ing("rice", "Rice"), _ing("yams", "Yams"),
        _ing("plantains", "Plantains"), _ing("cassava", "Cassava (Garri)"),
        _ing("palm_oil", "Palm Oil"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("ginger", "Ginger"),
        _ing("tomatoes", "Tomatoes"), _ing("scotch_bonnet", "Scotch Bonnet Pepper"),
        _ing("chicken", "Chicken"), _ing("beef", "Beef"),
        _ing("goat", "Goat"), _ing("stockfish", "Stockfish"),
        _ing("crayfish", "Crayfish (Ground)"), _ing("egusi", "Egusi (Melon Seeds)"),
        _ing("okra", "Okra"), _ing("spinach_ng", "Spinach (Efo/Ugu)"),
        _ing("black_eyed_peas", "Black-Eyed Peas"),
        _ing("peanuts", "Peanuts (Groundnuts)"),
        _ing("locust_beans", "Locust Beans (Iru/Ogiri)"),
        _ing("corn", "Corn"), _ing("beans", "Honey Beans"),
        _ing("bell_peppers", "Bell Peppers"), _ing("curry_powder", "Curry Powder"),
        _ing("thyme", "Thyme"), _ing("suya_spice", "Suya Spice"),
        _ing("jollof_seasoning", "Jollof Seasoning"),
    ],

    # ── Oceanian (region default) ───────────────────────────────────────
    "oceanian": [
        _ing("lamb", "Lamb"), _ing("beef", "Beef"), _ing("chicken", "Chicken"),
        _ing("shrimp", "Prawns"), _ing("fish", "Fish (Barramundi/Snapper)"),
        _ing("sweet_potato", "Sweet Potato (Kumara)"),
        _ing("potatoes", "Potatoes"), _ing("onions", "Onions"),
        _ing("garlic", "Garlic"), _ing("tomatoes", "Tomatoes"),
        _ing("avocado", "Avocado"), _ing("lemon", "Lemon"),
        _ing("lime", "Lime"), _ing("coconut_milk", "Coconut Milk"),
        _ing("macadamia", "Macadamia Nuts"), _ing("pumpkin", "Pumpkin"),
        _ing("corn", "Corn"), _ing("mushrooms", "Mushrooms"),
        _ing("eggs", "Eggs"), _ing("kangaroo", "Kangaroo"),
        _ing("cream", "Cream"), _ing("cheese", "Cheese"),
        _ing("olive_oil", "Olive Oil"), _ing("spinach", "Spinach"),
        _ing("zucchini", "Zucchini"), _ing("beetroot", "Beetroot"),
        _ing("mango", "Mango"), _ing("pineapple", "Pineapple"),
    ],
}

# Map of cuisine IDs to their parent region IDs for fallback lookup
CUISINE_TO_REGION = {
    "swedish": "nordic", "danish": "nordic", "norwegian": "nordic",
    "finnish": "nordic", "icelandic": "nordic", "new_nordic": "nordic",
    "japanese": "east_asian", "chinese": "east_asian", "korean": "east_asian",
    "taiwanese": "east_asian",
    "thai": "southeast_asian", "vietnamese": "southeast_asian",
    "indonesian": "southeast_asian", "malaysian": "southeast_asian",
    "filipino": "southeast_asian", "singaporean": "southeast_asian",
    "indian": "south_asian", "sri_lankan": "south_asian",
    "pakistani": "south_asian", "bangladeshi": "south_asian",
    "nepali": "south_asian",
    "lebanese": "middle_east", "turkish": "middle_east",
    "persian": "middle_east", "israeli": "middle_east",
    "syrian": "middle_east", "iraqi": "middle_east",
    "yemeni": "middle_east", "emirati": "middle_east",
    "palestinian": "middle_east",
    "italian": "european", "french": "european", "spanish": "european",
    "greek": "european", "portuguese": "european", "german": "european",
    "british": "european", "polish": "european", "hungarian": "european",
    "mediterranean": "european", "balkan": "european", "russian": "european",
    "american": "north_american", "cajun_creole": "north_american",
    "tex_mex": "north_american", "canadian": "north_american",
    "southern_us": "north_american", "hawaiian": "north_american",
    "mexican": "latin_american", "brazilian": "latin_american",
    "peruvian": "latin_american", "argentinian": "latin_american",
    "colombian": "latin_american", "cuban": "latin_american",
    "venezuelan": "latin_american", "chilean": "latin_american",
    "jamaican": "caribbean_region", "trinidadian": "caribbean_region",
    "haitian": "caribbean_region", "puerto_rican": "caribbean_region",
    "caribbean": "caribbean_region",
    "ethiopian": "african", "moroccan": "african", "nigerian": "african",
    "ghanaian": "african", "senegalese": "african", "south_african": "african",
    "kenyan": "african", "tanzanian": "african", "tunisian": "african",
    "egyptian": "african", "east_african": "african", "west_african": "african",
    "australian": "oceanian", "polynesian": "oceanian",
}
