"""
AI Recipe Builder Static Data

This file contains the static data for the AI Recipe Builder that can be
imported during frontend generation without requiring Home Assistant.
"""

# Cooking styles for AI recipe generation
COOKING_STYLES = [
    {"id": "quick_and_easy",  "name": "Quick And Easy",   "name_sv": "Snabbt och enkelt"},
    {"id": "comfort_food",    "name": "Comfort Food",     "name_sv": "Husmanskost"},
    {"id": "family_friendly", "name": "Family Friendly",  "name_sv": "Familjevänligt"},
    {"id": "healthy",         "name": "Healthy",          "name_sv": "Hälsosamt"},
    {"id": "gourmet",         "name": "Gourmet",          "name_sv": "Gourmet"},
    {"id": "meal_prep",       "name": "Meal Prep",        "name_sv": "Förberedd mat"},
    {"id": "one_pot",         "name": "One Pot",          "name_sv": "Engrytarätt"},
    {"id": "slow_cook",       "name": "Slow Cook",        "name_sv": "Långkok"},
    {"id": "barbeque",        "name": "Barbeque",         "name_sv": "Grillat"},
    {"id": "baking",          "name": "Baking",           "name_sv": "Bakning"},
    {"id": "low_carb",        "name": "Low Carb",         "name_sv": "Lågkolhydrat"},
    {"id": "high_protein",    "name": "High Protein",     "name_sv": "Proteinrikt"},
    {"id": "vegetarian",      "name": "Vegetarian",       "name_sv": "Vegetariskt"},
    {"id": "vegan",           "name": "Vegan",            "name_sv": "Veganskt"},
]

# Common ingredients grouped by category (default when no cuisine selected).
#
# Each item carries a ``common`` flag:
#   common=True  → shown in the default (compact) view
#   common=False → revealed only when the user taps "More" in that category
#
# The base view per category shows all common=True items.  The extended view
# shows everything.  Keep the common=True subset at roughly 8–12 per category
# so the picker stays compact by default.
COMMON_INGREDIENTS = {
    "proteins": [
        # Base set — shown by default
        {"id": "chicken_breast",  "name": "Chicken Breast",        "featured": True},
        {"id": "chicken_thigh",   "name": "Chicken Thighs",        "featured": True},
        {"id": "ground_beef",     "name": "Ground Beef",           "featured": True},
        {"id": "steak",           "name": "Steak (Beef)",          "featured": True},
        {"id": "pork_chop",       "name": "Pork Chops",            "featured": True},
        {"id": "salmon",          "name": "Salmon",                "featured": True},
        {"id": "shrimp",          "name": "Shrimp",                "featured": True},
        {"id": "tofu",            "name": "Tofu",                  "featured": True},
        {"id": "eggs",            "name": "Eggs",                  "featured": True},
        # Extended set — visible after "More"
        {"id": "cod",             "name": "Cod",                   "featured": False},
        {"id": "tuna",            "name": "Tuna",                  "featured": False},
        {"id": "lamb",            "name": "Lamb",                  "featured": False},
        {"id": "duck",            "name": "Duck",                  "featured": False},
        {"id": "turkey",          "name": "Turkey",                "featured": False},
        {"id": "pork_belly",      "name": "Pork Belly",            "featured": False},
        {"id": "bacon",           "name": "Bacon",                 "featured": False},
        {"id": "sausage",         "name": "Sausage",               "featured": False},
        {"id": "mussels",         "name": "Mussels",               "featured": False},
        {"id": "crab",            "name": "Crab",                  "featured": False},
        {"id": "herring",         "name": "Herring",               "featured": False},
        {"id": "paneer",          "name": "Paneer",                "featured": False},
        {"id": "tempeh",          "name": "Tempeh",                "featured": False},
        {"id": "anchovies",       "name": "Anchovies",             "featured": False},
    ],
    "vegetables": [
        # Base set — shown by default
        {"id": "broccoli",        "name": "Broccoli",              "featured": True},
        {"id": "carrots",         "name": "Carrots",               "featured": True},
        {"id": "bell_peppers",    "name": "Bell Peppers",          "featured": True},
        {"id": "onions",          "name": "Onions",                "featured": True},
        {"id": "garlic",          "name": "Garlic",                "featured": True},
        {"id": "tomatoes",        "name": "Tomatoes",              "featured": True},
        {"id": "spinach",         "name": "Spinach",               "featured": True},
        {"id": "potatoes",        "name": "Potatoes",              "featured": True},
        {"id": "sweet_potatoes",  "name": "Sweet Potatoes",        "featured": True},
        {"id": "zucchini",        "name": "Zucchini",              "featured": True},
        {"id": "cauliflower",     "name": "Cauliflower",           "featured": True},
        {"id": "green_beans",     "name": "Green Beans",           "featured": True},
        # Extended set — visible after "More"
        {"id": "mushrooms",       "name": "Mushrooms",             "featured": False},
        {"id": "eggplant",        "name": "Eggplant / Aubergine",  "featured": False},
        {"id": "celery",          "name": "Celery",                "featured": False},
        {"id": "leeks",           "name": "Leeks",                 "featured": False},
        {"id": "cabbage",         "name": "Cabbage",               "featured": False},
        {"id": "peas",            "name": "Peas",                  "featured": False},
        {"id": "corn",            "name": "Corn",                  "featured": False},
        {"id": "cucumber",        "name": "Cucumber",              "featured": False},
        {"id": "avocado",         "name": "Avocado",               "featured": False},
        {"id": "beets",           "name": "Beets",                 "featured": False},
        {"id": "artichokes",      "name": "Artichokes",            "featured": False},
        {"id": "pumpkin",         "name": "Pumpkin / Squash",      "featured": False},
        {"id": "fennel",          "name": "Fennel",                "featured": False},
        {"id": "okra",            "name": "Okra",                  "featured": False},
        {"id": "parsnips",        "name": "Parsnips",              "featured": False},
        {"id": "turnips",         "name": "Turnips",               "featured": False},
    ],
    "grains": [
        # Base set — shown by default
        {"id": "rice",            "name": "Rice",                  "featured": True},
        {"id": "pasta",           "name": "Pasta",                 "featured": True},
        {"id": "quinoa",          "name": "Quinoa",                "featured": True},
        {"id": "bread",           "name": "Bread",                 "featured": True},
        {"id": "tortillas",       "name": "Tortillas",             "featured": True},
        # Extended set — visible after "More"
        {"id": "lentils",         "name": "Lentils",               "featured": False},
        {"id": "chickpeas",       "name": "Chickpeas",             "featured": False},
        {"id": "black_beans",     "name": "Black Beans",           "featured": False},
        {"id": "kidney_beans",    "name": "Kidney Beans",          "featured": False},
        {"id": "oats",            "name": "Oats",                  "featured": False},
        {"id": "barley",          "name": "Barley",                "featured": False},
        {"id": "couscous",        "name": "Couscous",              "featured": False},
        {"id": "polenta",         "name": "Polenta / Cornmeal",    "featured": False},
        {"id": "noodles",         "name": "Noodles",               "featured": False},
        {"id": "pita",            "name": "Pita Bread",            "featured": False},
        {"id": "flour",           "name": "Flour",                 "featured": False},
    ],
    "dairy": [
        # This category maps to the "Dairy, Oils & Sauces" label (see CATEGORY_LABELS["d"]).
        # It intentionally includes non-dairy pantry staples (oils, sauces, condiments) because
        # the UI renders it under the broader "🫙 Dairy, Oils & Sauces" heading.
        # Base set — shown by default
        {"id": "cheese",          "name": "Cheese",                "featured": True},
        {"id": "milk",            "name": "Milk",                  "featured": True},
        {"id": "butter",          "name": "Butter",                "featured": True},
        {"id": "cream",           "name": "Cream",                 "featured": True},
        {"id": "yogurt",          "name": "Yogurt",                "featured": True},
        # Extended set — visible after "More"
        {"id": "sour_cream",      "name": "Sour Cream",            "featured": False},
        {"id": "cream_cheese",    "name": "Cream Cheese",          "featured": False},
        {"id": "parmesan",        "name": "Parmesan",              "featured": False},
        {"id": "feta",            "name": "Feta",                  "featured": False},
        {"id": "mozzarella",      "name": "Mozzarella",            "featured": False},
        {"id": "cheddar",         "name": "Cheddar",               "featured": False},
        {"id": "coconut_milk",    "name": "Coconut Milk",          "featured": False},
        {"id": "olive_oil",       "name": "Olive Oil",             "featured": False},
        {"id": "soy_sauce",       "name": "Soy Sauce",             "featured": False},
        {"id": "tomato_paste",    "name": "Tomato Paste",          "featured": False},
        {"id": "mustard",         "name": "Mustard",               "featured": False},
        {"id": "honey",           "name": "Honey",                 "featured": False},
    ],
    "spices": [
        # Base set — shown by default
        {"id": "cumin",           "name": "Cumin",                 "featured": True},
        {"id": "paprika",         "name": "Paprika",               "featured": True},
        {"id": "cinnamon",        "name": "Cinnamon",              "featured": True},
        {"id": "turmeric",        "name": "Turmeric",              "featured": True},
        {"id": "coriander",       "name": "Coriander",             "featured": True},
        {"id": "chili_powder",    "name": "Chili Powder",          "featured": True},
        {"id": "garam_masala",    "name": "Garam Masala",          "featured": True},
        {"id": "oregano",         "name": "Oregano",               "featured": True},
        # Extended set — visible after "More"
        {"id": "thyme",           "name": "Thyme",                 "featured": False},
        {"id": "rosemary",        "name": "Rosemary",              "featured": False},
        {"id": "basil",           "name": "Basil",                 "featured": False},
        {"id": "mint",            "name": "Mint",                  "featured": False},
        {"id": "dill",            "name": "Dill",                  "featured": False},
        {"id": "parsley",         "name": "Parsley",               "featured": False},
        {"id": "cilantro",        "name": "Cilantro",              "featured": False},
        {"id": "star_anise",      "name": "Star Anise",            "featured": False},
        {"id": "cardamom",        "name": "Cardamom",              "featured": False},
        {"id": "saffron",         "name": "Saffron",               "featured": False},
        {"id": "five_spice",      "name": "Five Spice",            "featured": False},
        {"id": "ras_el_hanout",   "name": "Ras el Hanout",         "featured": False},
        {"id": "sumac",           "name": "Sumac",                 "featured": False},
        {"id": "berbere",         "name": "Berbere",               "featured": False},
        {"id": "sesame_seeds",    "name": "Sesame Seeds",          "featured": False},
        {"id": "peanuts",         "name": "Peanuts",               "featured": False},
        {"id": "almonds",         "name": "Almonds",               "featured": False},
        {"id": "walnuts",         "name": "Walnuts",               "featured": False},
        {"id": "pine_nuts",       "name": "Pine Nuts",             "featured": False},
    ],
}

# ---------------------------------------------------------------------------
# Assumed staples — these are assumed to be available in every kitchen.
# They are NOT shown in the ingredient picker but are mentioned in the AI
# prompt so the AI knows it can use them.
# ---------------------------------------------------------------------------
ASSUMED_STAPLES = [
    "Cooking oil", "Butter", "Salt", "Black pepper", "Sugar", "Vinegar",
]

# Swedish versions of assumed staples (shown in UI when language=sv)
ASSUMED_STAPLES_SV = [
    "Matolja", "Smör", "Salt", "Svartpeppar", "Socker", "Vinäger",
]

# ---------------------------------------------------------------------------
# Swedish ingredient name lookup — maps ingredient ID → Swedish display name.
# Only used for the UI label; the English `name` is always sent to the AI.
# ---------------------------------------------------------------------------
INGREDIENT_NAMES_SV = {
    # Proteins
    "chicken_breast":   "Kycklingfilé",
    "chicken_thigh":    "Kycklinglår",
    "chicken":          "Kyckling",
    "ground_beef":      "Nötfärs",
    "steak":            "Biff",
    "beef":             "Nötkött",
    "pork_chop":        "Fläskkotlett",
    "pork":             "Fläskkött",
    "pork_belly":       "Sidfläsk",
    "salmon":           "Lax",
    "shrimp":           "Räkor",
    "tofu":             "Tofu",
    "eggs":             "Ägg",
    "lamb":             "Lammkött",
    "lamb_shank":       "Lammlägg",
    "duck":             "Anka",
    "turkey":           "Kalkon",
    "goat":             "Getkött",
    "fish":             "Fisk",
    "cod":              "Torsk",
    "herring":          "Sill",
    "tuna":             "Tonfisk",
    "canned_tuna":      "Konserverad tonfisk",
    "crab":             "Krabba",
    "mussels":          "Musslor",
    "bacon":            "Bacon",
    "pancetta":         "Pancetta",
    "prosciutto":       "Prosciutto",
    "jamon":            "Serranoskinka",
    "chorizo":          "Chorizo",
    "chorizo_ar":       "Chorizo",
    "sausage":          "Korv",
    "andouille":        "Andouille-korv",
    "lardons":          "Fläskbitar",
    "ham_hocks":        "Fläsklägg",
    "meatball_mix":     "Köttfärs (Fläsk/Nöt)",
    "tempeh":           "Tempeh",
    "paneer":           "Paneer",
    "catfish":          "Havskatt",
    "kangaroo":         "Kängurukött",
    "anchovies":        "Ansjovis",
    "dried_shrimp":     "Torkad räka",
    "edamame":          "Edamame",
    "stockfish":        "Torrfisk",
    "saltfish":         "Saltfisk",
    "crawfish":         "Kräftor",
    "crayfish":         "Kräftor",
    # Vegetables & Produce
    "broccoli":         "Broccoli",
    "carrots":          "Morötter",
    "bell_peppers":     "Paprika",
    "onions":           "Lök",
    "garlic":           "Vitlök",
    "tomatoes":         "Tomater",
    "spinach":          "Spenat",
    "spinach_ng":       "Spenat",
    "potatoes":         "Potatis",
    "sweet_potatoes":   "Sötpotatis",
    "sweet_potato":     "Sötpotatis",
    "zucchini":         "Zucchini",
    "cauliflower":      "Blomkål",
    "green_beans":      "Haricots verts",
    "mushrooms":        "Svamp",
    "shiitake":         "Shiitakesvamp",
    "eggplant":         "Aubergine",
    "cucumber":         "Gurka",
    "celery":           "Selleri",
    "leeks":            "Purjolök",
    "shallots":         "Schalottenlök",
    "green_onions":     "Salladslök",
    "spring_onions":    "Vårlök",
    "chives":           "Gräslök",
    "lettuce":          "Sallad",
    "cabbage":          "Kål",
    "chinese_cabbage":  "Napakål",
    "napa_cabbage":     "Napakål",
    "bok_choy":         "Pak choi",
    "beets":            "Rödbetor",
    "beetroot":         "Rödbeta",
    "parsnips":         "Palsternacka",
    "turnips":          "Rovor",
    "turnip":           "Rova",
    "artichokes":       "Kronärtskocka",
    "avocado":          "Avokado",
    "mango":            "Mango",
    "pineapple":        "Ananas",
    "banana":           "Banan",
    "banana_leaf":      "Bananblad",
    "papaya":           "Papaya",
    "green_papaya":     "Grön papaya",
    "pumpkin":          "Pumpa",
    "squash":           "Butternutpumpa",
    "okra":             "Okra",
    "corn":             "Majs",
    "fennel":           "Fänkål",
    "peas":             "Ärtor",
    "plantains":        "Plantain",
    "yam":              "Jams",
    "yams":             "Jams",
    "cassava":          "Kassava",
    "yuca":             "Kassava",
    "breadfruit":       "Brödfrukter",
    "tomatillos":       "Tomatillos",
    "jalapenos":        "Jalapeños",
    "poblano":          "Poblano-peppar",
    "ancho":            "Anchochili",
    "chipotle":         "Chipotle",
    "scotch_bonnet":    "Scotch Bonnet-peppar",
    "thai_chili":       "Thaichili",
    "lemongrass":       "Citrongräs",
    "kaffir_lime":      "Kaffirlimeblad",
    "galangal":         "Galangal",
    "ginger":           "Ingefära",
    "daikon":           "Daikon-rättika",
    "korean_radish":    "Koreansk rättika",
    "radish":           "Rättika",
    "bamboo_shoots":    "Bambusskott",
    "bean_sprouts":     "Böngroddar",
    "water_chestnuts":  "Vattenkastanjer",
    "morning_glory":    "Vattenspenat",
    "hearts_of_palm":   "Palmhjärtan",
    "callaloo":         "Callaloo",
    "ackee":            "Ackee",
    "horseradish":      "Pepparrot",
    "lingonberries":    "Lingon",
    "celeriac":         "Rotselleri",
    "juniper_berries":  "Enbär",
    "dill":             "Dill",
    "parsley":          "Persilja",
    "basil":            "Basilika",
    "basil_tw":         "Thaibasilika",
    "thai_basil":       "Thaibasilika",
    "mint":             "Mynta",
    "cilantro":         "Koriander",
    "oregano":          "Oregano",
    "rosemary":         "Rosmarin",
    "thyme":            "Timjan",
    "tarragon":         "Dragon",
    "bay_leaves":       "Lagerblad",
    "perilla":          "Perillablad",
    "pandan":           "Pandanblad",
    "herbs_mix":        "Färska örter (persilja, dill, koriander)",
    "grape_leaves":     "Vinblad",
    "ridge_gourd":      "Trumpetpumpa",
    "collard_greens":   "Collardkål",
    # Grains & Starches
    "rice":             "Ris",
    "pasta":            "Pasta",
    "quinoa":           "Quinoa",
    "bread":            "Bröd",
    "tortillas":        "Tortillas",
    "corn_tortillas":   "Majstortillas",
    "flour_tortillas":  "Mjöltortillas",
    "taco_shells":      "Tacoskal",
    "ciabatta":         "Ciabatta",
    "flat_bread":       "Flatbröd",
    "beans":            "Bönor",
    "rye_bread":        "Rågbröd",
    "baguette":         "Baguette",
    "pita":             "Pitabröd",
    "lavash":           "Lavashbröd",
    "basmati_rice":     "Basmatiris",
    "jasmine_rice":     "Jasminris",
    "arborio_rice":     "Arborioris",
    "bulgur":           "Bulgur",
    "couscous":         "Couscous",
    "barley":           "Korn",
    "oats":             "Havregryn",
    "flour":            "Mjöl",
    "cornmeal":         "Majsmjöl",
    "polenta":          "Polenta",
    "cornbread":        "Majsbröd",
    "noodles":          "Nudlar",
    "egg_noodles":      "Äggnooodles",
    "rice_noodles":     "Risnudlar",
    "rice_paper":       "Rispapper",
    "udon":             "Udonnudlar",
    "soba":             "Sobanudlar",
    "japchae_noodles":  "Sötpotatisnudlar",
    "rice_cakes":       "Riskakor",
    "panko":            "Pankoströbröd",
    "phyllo":           "Filodeg",
    "empanada_dough":   "Empanadedeg",
    "biscuit_dough":    "Biskedeg",
    "freekeh":          "Freekeh",
    "wonton_wrappers":  "Wonton-deg",
    "grits":            "Majsgröt",
    # Dairy, Oils & Sauces
    "cheese":           "Ost",
    "milk":             "Mjölk",
    "butter":           "Smör",
    "cream":            "Grädde",
    "heavy_cream":      "Vispgrädde",
    "yogurt":           "Yoghurt",
    "sour_cream":       "Gräddfil",
    "cream_cheese":     "Färskost",
    "creme_fraiche":    "Crème fraîche",
    "buttermilk":       "Kärnmjölk",
    "condensed_milk":   "Kondenserad mjölk",
    "evaporated_milk":  "Kondenserad mjölk (osötad)",
    "feta":             "Fetaost",
    "mozzarella":       "Mozzarella",
    "parmesan":         "Parmesanost",
    "cheddar":          "Cheddarsost",
    "gruyere":          "Gruyère-ost",
    "ricotta":          "Ricotta",
    "manchego":         "Manchego-ost",
    "pecorino":         "Pecorinoos",
    "monterey_jack":    "Monterey Jack-ost",
    "provolone":        "Provolone-ost",
    "cotija":           "Cotija-ost",
    "queso_fresco":     "Queso Fresco",
    "queso":            "Quesoost",
    "olive_oil":        "Olivolja",
    "sesame_oil":       "Sesamolja",
    "ghee":             "Ghee",
    "palm_oil":         "Palmolja",
    "niter_kibbeh":     "Niter Kibbeh (kryddsmör)",
    "herb_butter":      "Örtssmör",
    "dulce_de_leche":   "Dulce de Leche",
    "coconut_milk":     "Kokosmjölk",
    "tomato_paste":     "Tomatpuré",
    "soy_sauce":        "Soja",
    "fish_sauce":       "Fisksås",
    "oyster_sauce":     "Ostronsås",
    "hoisin_sauce":     "Hoisinsås",
    "miso_paste":       "Misopaste",
    "gochujang":        "Gochujang (chilipaste)",
    "doenjang":         "Doenjang (sojabönspaste)",
    "doubanjiang":      "Doubanjiangsås",
    "kecap_manis":      "Kecap Manis (söt soja)",
    "shrimp_paste":     "Räkpaste",
    "tamarind":         "Tamarind",
    "tamarind_paste":   "Tamarindpaste",
    "chili_paste":      "Chilipaste",
    "chili_oil":        "Chiliolja",
    "sriracha":         "Sriracha",
    "hot_sauce":        "Chilisås",
    "bbq_sauce":        "BBQ-sås",
    "salsa":            "Salsa",
    "dijon":            "Dijonsenap",
    "mustard":          "Senap",
    "worcestershire":   "Worcestershiresås",
    "tahini":           "Tahini",
    "pomegranate_molasses": "Granatäppelsirap",
    "red_wine":         "Rödvin",
    "white_wine":       "Vitt vin",
    "wine_white":       "Vitt vin",
    "rice_wine":        "Risvin",
    "rice_vinegar":     "Risvinäger",
    "red_wine_vinegar": "Rödvinsvinäger",
    "sherry_vinegar":   "Sherryvinäger",
    "balsamic":         "Balsamvinäger",
    "mirin":            "Mirin",
    "black_vinegar":    "Svart vinäger",
    "maple_syrup":      "Lönnsirap",
    "molasses":         "Melass",
    "honey":            "Honung",
    "jaggery":          "Jaggery",
    "palm_sugar":       "Palmsocker",
    "brown_sugar":      "Råsocker",
    "sugar_cane":       "Råsocker",
    "preserved_lemons": "Inlagd citron",
    "capers":           "Kapris",
    "lemon":            "Citron",
    "lime":             "Lime",
    "calamansi":        "Kalamansi (lime)",
    "san_marzano":      "San Marzano-tomater",
    "cannellini":       "Cannellinibönor",
    "kidney_beans":     "Kidney-bönor",
    "red_beans":        "Röda bönor",
    "black_beans":      "Svarta bönor",
    "pinto_beans":      "Pintobönor",
    "chickpeas":        "Kikärtor",
    "lentils":          "Linser",
    "split_peas":       "Delade ärtor",
    "black_eyed_peas":  "Svartögade bönor",
    "refried_beans":    "Stekta bönor",
    "peas":             "Ärtor",
    "olives":           "Oliver",
    "dried_apricots":   "Torkade aprikoser",
    "apricots":         "Torkade aprikoser",
    "dates":            "Dadlar",
    "barberries":       "Berberisbär",
    "sour_cherries":    "Surkörsbär",
    "pomegranate":      "Granatäpple",
    "quince":           "Kvitten",
    "nori":             "Nori (tång)",
    "seaweed":          "Tång",
    "dried_seaweed":    "Torkad tång",
    "kombu":            "Kombu",
    "bonito":           "Bonitoflingor",
    "kimchi":           "Kimchi",
    "pickled_ginger":   "Inlagd ingefära",
    "coconut":          "Kokosnöt",
    # Spices, Nuts & Seasonings
    "paprika":          "Paprikapulver",
    "cumin":            "Spiskummin",
    "coriander":        "Koriander (malen)",
    "turmeric":         "Gurkmeja",
    "garam_masala":     "Garam masala",
    "curry_powder":     "Karrypulver",
    "curry_leaves":     "Curryblad",
    "cardamom":         "Kardemumma",
    "cinnamon":         "Kanel",
    "cloves":           "Kryddnejlika",
    "nutmeg":           "Muskot",
    "allspice":         "Kryddpeppar",
    "star_anise":       "Stjärnanis",
    "five_spice":       "Fem-kryddpulver",
    "szechuan_pepper":  "Szechuanpeppar",
    "white_pepper":     "Vitpeppar",
    "cayenne":          "Cayennepeppar",
    "chili_powder":     "Chilipulver",
    "red_pepper_flakes": "Chiliflingor",
    "chili":            "Chili",
    "gochugaru":        "Gochugaru (chiliflingor)",
    "berbere":          "Berbere-krydda",
    "ras_el_hanout":    "Ras el Hanout",
    "sumac":            "Sumak",
    "zaatar":           "Za'atar",
    "saffron":          "Saffran",
    "fenugreek":        "Bockhornsklöver",
    "mustard_seeds":    "Senapsfrön",
    "asafoetida":       "Asafoetida",
    "amchur":           "Mangopulver",
    "mitmita":          "Mitmita-krydda",
    "korerima":         "Etiopisk kardemumma",
    "suya_spice":       "Suya-krydda",
    "jollof_seasoning": "Jollof-krydda",
    "berbere":          "Berbere-krydda",
    "nigella_seeds":    "Svartkummin",
    "peppercorns":      "Svartpepparkorn",
    "annatto":          "Annatto-frön",
    "achiote":          "Achiote",
    "epazote":          "Epazote",
    "huacatay":         "Huacatay (svart mynta)",
    "dried_mint":       "Torkad mynta",
    "dried_limes":      "Torkade limefrukter",
    "green_curry_paste": "Grön currypaste",
    "red_curry_paste":  "Röd currypaste",
    "rose_water":       "Rosenvatten",
    "candlenut":        "Ljusnöt",
    "almonds":          "Mandlar",
    "walnuts":          "Valnötter",
    "pine_nuts":        "Pinjenötter",
    "peanuts":          "Jordnötter",
    "pecans":           "Pekannötter",
    "pistachios":       "Pistaschnötter",
    "macadamia":        "Macadamianötter",
    "sesame_seeds":     "Sesamfrön",
    "corn_starch":      "Majsstärkelse",
    "rum":              "Rom",
    "chimichurri":      "Chimichurri-örter",
    "farofa":           "Farofa",
    "cancha":           "Rostad majs",
    "injera_flour":     "Teffmjöl",
    "egusi":            "Egusi (melonfrön)",
    "locust_beans":     "Locust-bönor",
    "crayfish":         "Torkad räka (mald)",
    "stockfish":        "Torrfisk",
    "aji_amarillo":     "Gul chilipeppar",
    "aji_panca":        "Ají Panca",
    "rocoto":           "Rocoto-peppar",
    "fermented_black_beans": "Fermenterade svarta bönor",
    "wasabi":           "Wasabi",
    "bok_choy":         "Pak choi",
    "hearts_of_palm":   "Palmhjärtan",
    "kokum":            "Kokum",
    "file_powder":      "Filépulver",
    "asafoetida":       "Asafoetida",
    "annatto":          "Annatto",
    # --- Added: proteins missing sv translation ---
    "goose":            "Gås",
    "lobster":          "Hummer",
    "mackerel":         "Makrill",
    "prawns":           "Havskräftor",
    "reindeer":         "Renkött",
    "trout":            "Forell",
    "rabbit":           "Kanin",
    "veal":             "Kalvkött",
    "venison":          "Viltkött",
    "octopus":          "Bläckfisk",
    "sardines":         "Sardiner",
    "clams":            "Havsmusslor",
    "ham":              "Skinka",
    "chourico":         "Chouriço",
    "presunto":         "Presunto",
    "shellfish":        "Skaldjur",
    "smoked_fish":      "Rökt fisk",
    "boerewors":        "Boerewors",
    "biltong":          "Biltong",
    # --- Added: vegetables/produce missing sv translation ---
    "apples":           "Äpplen",
    "apricot":          "Aprikos",
    "blueberries":      "Blåbär",
    "cloudberries":     "Hjortron",
    "raisins":          "Russin",
    "kale":             "Grönkål",
    "red_cabbage":      "Rödkål",
    "sauerkraut":       "Surkål",
    "kohlrabi":         "Kålrabbi",
    "watercress":       "Källkrasse",
    "bitter_melon":     "Bittermelon",
    "jackfruit":        "Jackfrukt",
    "fava_beans":       "Bondbönor",
    "pigeon_peas":      "Duvärtor",
    "taro":             "Taro",
    "green_chili":      "Grön chili",
    "sour_orange":      "Bitterapelsin",
    "molokhia":         "Molokhia",
    "ugu_leaves":       "Ugu-blad",
    "kenkey":           "Kenkey",
    # --- Added: grains/starches missing sv translation ---
    "buckwheat":        "Bovete",
    "millet":           "Hirs",
    "roti":             "Roti",
    "teff":             "Teff",
    "wild_rice":        "Vildris",
    # --- Added: dairy/oils/sauces missing sv translation ---
    "lard":             "Ister",
    "mustard_oil":      "Senapsolja",
    "argan_oil":        "Arganolja",
    "skyr":             "Skyr",
    "crema":            "Crema",
    "sofrito":          "Sofrito",
    "harissa":          "Harissa",
    "adobo_sauce":      "Adobo-sås",
    "teriyaki_sauce":   "Teriyakisås",
    "laksa_paste":      "Laksapasta",
    "beer":             "Öl",
    "pisco":            "Pisco",
    "mojo":             "Mojosås",
    "pepper_sauce":     "Pebbersås",
    "epis":             "Epis",
    "queso_blanco":     "Vit ost",
    # --- Added: spices/seasonings missing sv translation ---
    "black_pepper":     "Svartpeppar",
    "caraway_seeds":    "Kumminfrön",
    "marjoram":         "Mejram",
    "sea_buckthorn":    "Havtorn",
    "cape_malay_spice": "Kap Malaykryddor",
    "hawaij_spice":     "Hawaij-kryddor",
    "merken":           "Merkén",
    "timur":            "Timurpeppar",
    "goraka":           "Goraka",
    "malagueta":        "Malaguetapeppar",
    "piri_piri":        "Piri-piri",
    "shadow_beni":      "Shadow beni",
}

# ---------------------------------------------------------------------------
# Ingredient category mapping (used by frontend to group & sort ingredients).
#   p = Proteins   v = Produce   g = Grains & Starches
#   d = Dairy, Oils & Sauces     s = Spices, Nuts & Seasonings
# ---------------------------------------------------------------------------
INGREDIENT_CATEGORIES = {
    # Proteins
    "ackee": "p", "anchovies": "p", "andouille": "p", "bacon": "p",
    "beef": "p", "canned_tuna": "p", "catfish": "p", "chicken": "p",
    "chicken_breast": "p", "chicken_thigh": "p", "chorizo": "p",
    "chorizo_ar": "p", "cod": "p", "crab": "p", "crawfish": "p",
    "crayfish": "p", "dried_shrimp": "p", "duck": "p", "edamame": "p",
    "eggs": "p", "fish": "p", "goat": "p", "ground_beef": "p",
    "ham_hocks": "p", "herring": "p", "jamon": "p", "lamb": "p",
    "lamb_shank": "p", "lardons": "p", "meatball_mix": "p",
    "mussels": "p", "pancetta": "p", "paneer": "p", "pork": "p",
    "pork_belly": "p", "pork_chop": "p", "prosciutto": "p",
    "salmon": "p", "saltfish": "p", "sausage": "p", "shrimp": "p",
    "steak": "p", "stockfish": "p", "tempeh": "p", "tofu": "p",
    "tuna": "p", "turkey": "p",
    # New proteins
    "veal": "p", "venison": "p", "goose": "p", "rabbit": "p",
    "reindeer": "p", "kangaroo": "p", "octopus": "p", "sardines": "p",
    "trout": "p", "mackerel": "p", "clams": "p", "chourico": "p",
    "boerewors": "p", "biltong": "p", "lobster": "p", "prawns": "p",
    # Produce (vegetables, fruits, fresh herbs)
    "artichokes": "v", "avocado": "v", "bamboo_shoots": "v",
    "banana": "v", "banana_leaf": "v", "basil": "v", "basil_tw": "v",
    "bay_leaves": "v", "bean_sprouts": "v", "beetroot": "v", "beets": "v",
    "bell_peppers": "v", "bok_choy": "v", "breadfruit": "v",
    "broccoli": "v", "cabbage": "v", "calamansi": "v", "callaloo": "v",
    "carrots": "v", "cassava": "v", "cauliflower": "v", "celeriac": "v",
    "celery": "v", "chili": "v", "chinese_cabbage": "v", "chives": "v",
    "cilantro": "v", "collard_greens": "v", "corn": "v",
    "cucumber": "v", "curry_leaves": "v", "daikon": "v", "dill": "v",
    "eggplant": "v", "epazote": "v", "galangal": "v", "garlic": "v",
    "ginger": "v", "grape_leaves": "v", "green_beans": "v",
    "green_onions": "v", "green_papaya": "v", "herbs_mix": "v",
    "horseradish": "v", "jalapenos": "v", "kaffir_lime": "v",
    "korean_radish": "v", "leeks": "v", "lemon": "v", "lemongrass": "v",
    "lettuce": "v", "lime": "v", "mango": "v", "mint": "v",
    "morning_glory": "v", "mushrooms": "v", "napa_cabbage": "v",
    "okra": "v", "onions": "v", "oregano": "v", "pandan": "v",
    "papaya": "v", "parsley": "v", "parsnips": "v", "peas": "v",
    "perilla": "v", "pineapple": "v", "plantains": "v", "poblano": "v",
    "preserved_lemons": "v", "pumpkin": "v", "quince": "v",
    "radish": "v", "ridge_gourd": "v", "rosemary": "v",
    "san_marzano": "v", "scotch_bonnet": "v", "shallots": "v",
    "shiitake": "v", "spinach": "v", "spinach_ng": "v",
    "spring_onions": "v", "squash": "v", "sweet_potato": "v",
    "sweet_potatoes": "v", "tarragon": "v", "thai_basil": "v",
    "thai_chili": "v", "thyme": "v", "tomatillos": "v", "tomatoes": "v",
    "turnip": "v", "turnips": "v", "water_chestnuts": "v", "yam": "v",
    "yams": "v", "yuca": "v", "zucchini": "v", "fennel": "v",
    # New produce
    "red_cabbage": "v", "apples": "v", "shadow_beni": "v",
    "sauerkraut": "v", "jackfruit": "v", "bitter_melon": "v",
    "kale": "v", "watercress": "v", "kohlrabi": "v",
    # Grains & Starches (incl. legumes, bread, noodles)
    "arborio_rice": "g", "baguette": "g", "barley": "g",
    "basmati_rice": "g", "beans": "g", "biscuit_dough": "g",
    "black_beans": "g", "black_eyed_peas": "g", "bread": "g",
    "bulgur": "g", "cannellini": "g", "chickpeas": "g",
    "ciabatta": "g", "corn_tortillas": "g", "cornbread": "g",
    "cornmeal": "g", "couscous": "g", "egg_noodles": "g",
    "polenta": "g",
    "empanada_dough": "g", "farofa": "g", "flat_bread": "g",
    "flour": "g", "flour_tortillas": "g", "freekeh": "g", "grits": "g",
    "injera_flour": "g", "japchae_noodles": "g", "jasmine_rice": "g",
    "kidney_beans": "g", "lavash": "g", "lentils": "g", "noodles": "g",
    "oats": "g", "panko": "g", "pasta": "g", "phyllo": "g", "pinto_beans": "g",
    "pita": "g", "potatoes": "g", "quinoa": "g", "red_beans": "g",
    "rice": "g", "rice_cakes": "g", "rice_noodles": "g",
    "rice_paper": "g", "rye_bread": "g", "soba": "g", "split_peas": "g",
    "taco_shells": "g", "tortillas": "g", "udon": "g",
    "wonton_wrappers": "g",
    # New grains/starches
    "buckwheat": "g", "pigeon_peas": "g", "fava_beans": "g",
    "kenkey": "g", "roti": "g", "wild_rice": "g", "teff": "g",
    "millet": "g", "taro": "g",
    # Dairy, Oils & Sauces
    "balsamic": "d", "bbq_sauce": "d", "black_vinegar": "d",
    "butter": "d", "buttermilk": "d", "cheddar": "d", "cheese": "d", "chili_oil": "d",
    "chili_paste": "d", "coconut": "d", "coconut_milk": "d",
    "condensed_milk": "d", "cotija": "d", "cream": "d",
    "cream_cheese": "d", "creme_fraiche": "d", "dijon": "d",
    "doenjang": "d", "doubanjiang": "d", "dulce_de_leche": "d",
    "evaporated_milk": "d", "feta": "d", "fish_sauce": "d", "ghee": "d",
    "gochujang": "d", "green_curry_paste": "d", "gruyere": "d",
    "heavy_cream": "d", "herb_butter": "d", "hoisin_sauce": "d",
    "honey": "d", "hot_sauce": "d", "kecap_manis": "d", "kimchi": "d",
    "manchego": "d", "maple_syrup": "d", "milk": "d", "mirin": "d",
    "miso_paste": "d", "molasses": "d", "monterey_jack": "d",
    "mozzarella": "d", "mustard": "d", "niter_kibbeh": "d",
    "olive_oil": "d", "oyster_sauce": "d", "palm_oil": "d",
    "parmesan": "d", "pecorino": "d", "pomegranate_molasses": "d",
    "provolone": "d", "queso": "d", "queso_fresco": "d",
    "red_curry_paste": "d", "red_wine": "d", "red_wine_vinegar": "d",
    "refried_beans": "d", "rice_vinegar": "d", "rice_wine": "d",
    "ricotta": "d", "rose_water": "d", "rum": "d", "salsa": "d",
    "sesame_oil": "d", "sherry_vinegar": "d", "shrimp_paste": "d",
    "sour_cream": "d", "soy_sauce": "d", "sriracha": "d",
    "tahini": "d", "tamarind": "d", "tamarind_paste": "d",
    "tomato_paste": "d", "white_wine": "d", "wine_white": "d",
    "worcestershire": "d", "yogurt": "d",
    # New dairy/oils/sauces
    "sofrito": "d", "epis": "d", "harissa": "d", "piri_piri": "d",
    "lard": "d", "beer": "d", "laksa_paste": "d", "skyr": "d",
    "mustard_oil": "d", "goraka": "d", "coconut_cream": "d",
    "queso_blanco": "d", "teriyaki_sauce": "d", "adobo_sauce": "d",
    # Spices, Nuts & Seasonings
    "achiote": "s", "aji_amarillo": "s", "aji_panca": "s",
    "allspice": "s", "almonds": "s", "amchur": "s", "ancho": "s",
    "annatto": "s", "apricots": "s", "asafoetida": "s",
    "barberries": "s", "berbere": "s", "bonito": "s", "brown_sugar": "s",
    "cancha": "s", "candlenut": "s", "capers": "s", "cardamom": "s",
    "cayenne": "s", "chili_powder": "s", "chimichurri": "s",
    "chipotle": "s", "cinnamon": "s", "cloves": "s", "coriander": "s",
    "corn_starch": "s", "cumin": "s", "curry_powder": "s", "dates": "s",
    "dried_apricots": "s", "dried_limes": "s", "dried_mint": "s",
    "dried_seaweed": "s", "egusi": "s", "fenugreek": "s",
    "fermented_black_beans": "s", "file_powder": "s", "five_spice": "s",
    "garam_masala": "s", "gochugaru": "s", "hearts_of_palm": "s",
    "huacatay": "s", "jaggery": "s", "jollof_seasoning": "s",
    "juniper_berries": "s", "kokum": "s", "kombu": "s",
    "korerima": "s", "lingonberries": "s", "locust_beans": "s",
    "macadamia": "s", "mitmita": "s", "mustard_seeds": "s",
    "nigella_seeds": "s", "nori": "s", "nutmeg": "s", "olives": "s",
    "palm_sugar": "s", "paprika": "s", "peanuts": "s", "pecans": "s",
    "peppercorns": "s", "pickled_ginger": "s", "pine_nuts": "s",
    "pistachios": "s", "pomegranate": "s", "ras_el_hanout": "s",
    "red_pepper_flakes": "s", "rocoto": "s", "saffron": "s",
    "seaweed": "s", "sesame_seeds": "s", "sour_cherries": "s",
    "star_anise": "s", "sugar_cane": "s", "sumac": "s",
    "suya_spice": "s", "szechuan_pepper": "s", "turmeric": "s",
    "walnuts": "s", "wasabi": "s", "white_pepper": "s", "zaatar": "s",
    # New spices/nuts/seasonings
    "caraway_seeds": "s", "marjoram": "s", "poppy_seeds": "s",
    "merken": "s", "merkén": "s", "hawaij_spice": "s", "sazon": "s", "sazón": "s",
    "guava": "v",
    "chakalaka_spice": "s", "cape_malay_spice": "s", "berbere": "s",
    "timur": "s", "cloudberries": "s", "sea_buckthorn": "s",
    "raisins": "s", "bay_leaves": "s", "pepper_sauce": "s",
}

# Category display labels (used by frontend for section headers)
CATEGORY_LABELS = {
    "p": "🥩 Proteins",
    "v": "🥬 Produce",
    "g": "🌾 Grains & Starches",
    "d": "🫙 Dairy, Oils & Sauces",
    "s": "🌶️ Spices, Nuts & Seasonings",
}

# Swedish category display labels
CATEGORY_LABELS_SV = {
    "p": "🥩 Proteiner",
    "v": "🥬 Grönsaker & Frukt",
    "g": "🌾 Spannmål & Stärkelse",
    "d": "🫙 Mejeriprodukter, Oljor & Såser",
    "s": "🌶️ Kryddor, Nötter & Smaksättare",
}

# Category display order
CATEGORY_ORDER = ["p", "v", "g", "d", "s"]

# ---------------------------------------------------------------------------
# Cuisine-specific ingredients
#
# Keys can be either a region ID or an individual cuisine ID.
# Lookup order: individual cuisine ID -> parent region ID -> COMMON_INGREDIENTS
#
# Staples (oil, butter, salt, pepper, sugar, vinegar) are assumed available
# and NOT listed — freeing slots for more distinctive ingredients & proteins.
# ---------------------------------------------------------------------------

def _ing(id_str, name):
    """Common ingredient — shown by default in this cuisine's ingredient panel."""
    return {"id": id_str, "name": name, "featured": True}

def _inge(id_str, name):
    """Extended ingredient — hidden behind 'More' in this cuisine's ingredient panel.
    The same ingredient can be _ing() in one cuisine and _inge() in another."""
    return {"id": id_str, "name": name, "featured": False}

# ---------------------------------------------------------------------------
# Protein subcategory mapping — maps ingredient ID → dropdown subcategory.
#
# Used by the frontend to:
#   1. Highlight protein dropdown buttons (Beef/Pork/Poultry/Fish/Lamb/Game)
#      when any ingredient in that subcategory is common for the selected cuisine.
#   2. Highlight individual cuts inside a dropdown that match common cuisine proteins.
#
# GENERIC_PROTEIN_IDS: bare category names that duplicate the dropdown button
# labels — these are filtered from the badge list (the button IS the badge).
# All other specific IDs (salmon, chicken_thigh, pork_belly …) remain as badges
# AND additionally highlight the relevant button.
# ---------------------------------------------------------------------------
PROTEIN_TO_SUBCAT = {
    # Beef
    "beef": "beef", "ground_beef": "beef", "steak": "beef", "veal": "beef",
    "brisket": "beef", "chuck_roast": "beef", "short_ribs": "beef",
    "beef_tongue": "beef", "beef_liver": "beef",
    # Pork
    "pork": "pork", "pork_chop": "pork", "pork_belly": "pork",
    "bacon": "pork", "sausage": "pork", "ham_hocks": "pork",
    "lardons": "pork", "chorizo": "pork", "prosciutto": "pork",
    "andouille": "pork", "pancetta": "pork", "jamon": "pork",
    "meatball_mix": "pork", "chourico": "pork", "boerewors": "pork",
    # Poultry
    "chicken": "poultry", "chicken_breast": "poultry", "chicken_thigh": "poultry",
    "turkey": "poultry", "duck": "poultry", "goose": "poultry",
    # Fish & seafood
    "fish": "fish", "salmon": "fish", "cod": "fish", "tuna": "fish",
    "herring": "fish", "trout": "fish", "mackerel": "fish", "sardines": "fish",
    "catfish": "fish", "anchovies": "fish", "mussels": "fish",
    "crab": "fish", "shrimp": "fish", "lobster": "fish", "prawns": "fish",
    "clams": "fish", "octopus": "fish", "canned_tuna": "fish",
    "dried_shrimp": "fish", "saltfish": "fish", "stockfish": "fish",
    "crawfish": "fish", "crayfish": "fish",
    # Lamb / Goat
    "lamb": "lamb", "lamb_shank": "lamb", "goat": "lamb",
    # Game
    "venison": "game", "rabbit": "game", "kangaroo": "game", "reindeer": "game",
}

# Ingredient IDs that duplicate dropdown button labels — filtered from badge list.
GENERIC_PROTEIN_IDS = {
    "beef", "chicken", "pork", "fish", "lamb",
    "turkey", "duck", "goat", "veal", "venison", "rabbit",
}

# Cuisine-specific ingredient data has moved to www/cuisines/*.md (KCE:CUISINE files).
# This dict is kept only for backward compatibility; the generator reads the markdown files.
CUISINE_INGREDIENTS = {}

# Map of cuisine IDs to their parent region IDs for fallback lookup
CUISINE_TO_REGION = {
    "swedish": "nordic", "danish": "nordic", "norwegian": "nordic",
    "finnish": "nordic", "icelandic": "nordic", "new_nordic": "nordic",
    "japanese": "east_asian", "chinese": "east_asian", "korean": "east_asian",
    "taiwanese": "east_asian",
    "thai": "southeast_asian", "vietnamese": "southeast_asian",
    "indonesian": "southeast_asian", "malaysian": "southeast_asian",
    "filipino": "southeast_asian", "singaporean": "southeast_asian",
    "indian": "south_asian", "sri_lankan": "south_asian",
    "pakistani": "south_asian", "bangladeshi": "south_asian",
    "nepali": "south_asian",
    "lebanese": "middle_east", "turkish": "middle_east",
    "persian": "middle_east", "israeli": "middle_east",
    "syrian": "middle_east", "iraqi": "middle_east",
    "yemeni": "middle_east", "emirati": "middle_east",
    "palestinian": "middle_east",
    "italian": "european", "french": "european", "spanish": "european",
    "greek": "european", "portuguese": "european", "german": "european",
    "british": "european", "polish": "european", "hungarian": "european",
    "mediterranean": "european", "balkan": "european", "russian": "european",
    "american": "north_american", "cajun_creole": "north_american",
    "tex_mex": "north_american", "canadian": "north_american",
    "southern_us": "north_american", "hawaiian": "north_american",
    "mexican": "latin_american", "brazilian": "latin_american",
    "peruvian": "latin_american", "argentinian": "latin_american",
    "colombian": "latin_american", "cuban": "latin_american",
    "venezuelan": "latin_american", "chilean": "latin_american",
    "jamaican": "caribbean_region", "trinidadian": "caribbean_region",
    "haitian": "caribbean_region", "puerto_rican": "caribbean_region",
    "caribbean": "caribbean_region",
    "ethiopian": "african", "moroccan": "african", "nigerian": "african",
    "ghanaian": "african", "senegalese": "african", "south_african": "african",
    "kenyan": "african", "tanzanian": "african", "tunisian": "african",
    "egyptian": "african", "east_african": "african", "west_african": "african",
    "australian": "oceanian", "polynesian": "oceanian",
}
